// tbwd_d384.cu (research source: experiments/transition_fused_sm100/src/tbwd_d384.cu, branch perf/transition-sm100-b200; generated by export_engine.py)
// — the Transition backward at D = 384 (hidden HID = n D; n = 2 by default, 4 with -DHID=1536), bf16: the gate, the d_xn
// product and the LayerNorm backward + residual as ONE sm_100a kernel with 2-CTA tcgen05.mma (the two CTAs of a cluster run their own
// 128-row tiles in lockstep, the leader issues M = 256 products whose B operand is split by N across the pair), plus a small fixed-order
// reduction of the dgamma / dbeta partials. The weight gradients stay cuBLAS GEMMs over the dA | dB this kernel writes and the forward's h.
// Contract (tbwd.cu / tgate_ab.cu / tlnbwd_w.cu, from the forward's saved a, b, statistics):
//   dh = bf16(dy Ws)   sig = rcp(1 + ex2(-a log2 e))   silu = a sig   dA = bf16((dh b)(sig + silu(1 - sig)))   dB = bf16(dh silu)
//   d_xn = bf16(dA Wa + dB Wb)   xhat = (x - mean) rstd, w = gamma d_xn, dx = bf16(bf16((w - xhat ca - cb) rstd) + dy),
//   ca = mean(xhat w), cb = mean(w);  dgamma = sum d_xn xhat, dbeta = sum d_xn  (per-CTA partials, then this file's reduction)
// Per 64-unit hidden chunk c of a tile:
//   dh_c   = dy Ws_c          M 256, N 64 (32 units per CTA), K 384: A = the resident dy tile, B = this CTA's 32 rows of Ws^T (K-major)
//   gate   (warps 4-7 units 0..31, 12-15 units 32..63): dh from TMEM, a / b from shared memory (TMA), [dA | dB] back into dh's own TMEM
//          columns as bf16 (half by half, so each warpgroup overwrites only what it read), and to global memory for the dW GEMMs
//   d_xn  += [dA | dB]_c [Wa_c; Wb_c]   M 256, N 384 as 256 + 128, K 128: A from TMEM, B the weights in their own [H][D] layout (MN-major,
//          the 16-row blocks paired with the half-by-half A order as in tbwd.cu)
// Tensor memory: d_xn 384 columns + two 64-column dh / [dA | dB] buffers. Shared memory: the dy tile (96 KB; the A operand, then the
// residual and the dx staging), one Ws^T stage (24 KB), one [Wa_c; Wb_c] stage (48 KB), the chunk's a and b (32 KB); once a tile's last
// product is done its x tile is loaded over the weight / a-b region for the LayerNorm backward, which reads d_xn from TMEM with three
// threads per row (warps 4-15). SPDX-License-Identifier: Apache-2.0
#include "sm100.cuh"
using namespace s100;

#ifndef HID
#define HID 768                                                 // hidden units (n x D); n = 2 by default
#endif
constexpr int D_ = 384, H_ = HID, HS = 64, NCH = H_ / HS, ROWS = 128, NKB = D_ / 64;
static_assert(H_ % HS == 0 && NCH >= 2, "whole 64-unit chunks");
constexpr int KBT = ROWS * 128;                                // [128][64] bf16 tile, 16 KB
constexpr int TILE = NKB * KBT;                                // 96 KB
constexpr int WSK = 32 * 128;                                  // one K-block of this CTA's 32 Ws^T rows, 4 KB
constexpr int WS_SLOT = NKB * WSK;                             // 24 KB
constexpr int WAB_ATOM = 128 * 128;                            // [Wa_c 64 | Wb_c 64 unit rows][64 d], 128-B swizzled MN-major, 16 KB
constexpr int NATOM = 4;                                       // ring of atoms; a chunk takes three (d 128 a + 64 crank .. + 63, a = 0..2)
constexpr int O_DY = 0, O_X = O_DY + TILE, O_WS = O_X, O_WAB = O_WS + WS_SLOT, O_AB = O_WAB + NATOM * WAB_ATOM;
constexpr int O_GB = O_AB + 2 * KBT;
constexpr int O_EX = O_GB + D_ * 4;                            // LayerNorm row sums: [2][3 thirds][128 rows] fp32
constexpr int O_RED = O_X;                                     // dgamma | dbeta partials [4 lane quadrants][2 D] fp32, after the last tile
constexpr int O_BAR = O_EX + 6 * ROWS * 4;
constexpr int SMEM_BYTES = O_BAR + 512;
static_assert(SMEM_BYTES <= 232448, "shared memory budget");
static_assert(O_GB >= O_X + TILE, "the x tile fits the weight / a-b region");
static_assert(O_X % 1024 == 0 && O_WAB % 1024 == 0 && O_AB % 1024 == 0, "swizzle alignment");
constexpr uint32_t T_DXN = 0, T_DH = D_;                       // d_xn 384 | dh / [dA | dB] 2 x 64
constexpr uint32_t I_DH = idesc_bf16(256, 64), I_DX = idesc_bf16(256, 128, 0, 1);

// the 16-row block of the [Wa_c; Wb_c] atom matching A-operand K step ks of the half-by-half [dA | dB] layout
// (TMEM columns 0..15 dA(units 0..31), 16..31 dB(0..31), 32..47 dA(32..63), 48..63 dB(32..63))
__device__ constexpr int kRowBlk[8] = {0, 1, 4, 5, 2, 3, 6, 7};

// the gate on a pair of units in fp32x2 (tbwd.cu's gate_pair16, a / b from the forward's bf16)
DEVI void gate_pair(uint32_t dh0, uint32_t dh1, uint32_t ap, uint32_t bp, uint32_t& dap, uint32_t& dbp) {
  const uint32_t gp = pack_bf16(__uint_as_float(dh0), __uint_as_float(dh1));
  const f2 G = mk2(bf16lo(gp), bf16hi(gp)), A = mk2(bf16lo(ap), bf16hi(ap)), Bv = mk2(bf16lo(bp), bf16hi(bp));
  const f2 S = mk2(sigmoid_kit(lo2(A)), sigmoid_kit(hi2(A)));
  const f2 L = mul2(A, S);
  const f2 DB = mul2(G, L);
  const f2 U = fma2(L, fma2(S, mk2(-1.f, -1.f), mk2(1.f, 1.f)), S);
  const f2 DA = mul2(mul2(G, Bv), U);
  dap = pack_bf16(lo2(DA), hi2(DA)); dbp = pack_bf16(lo2(DB), hi2(DB));
}
// TMA prefetch of one box into L2 (no shared memory, no barrier)
DEVI void tma_prefetch_2d(const CUtensorMap* m, int c0, int c1) {
  asm volatile("cp.async.bulk.prefetch.tensor.2d.L2.global [%0, {%1, %2}];" :: "l"(m), "r"(c0), "r"(c1) : "memory");
}
// warp reduce-scatter: lane l returns the sum over the warp of v[l]
DEVI float reduce_scatter32(float (&v)[32], int lane) {
#pragma unroll
  for (int off = 16; off; off >>= 1) {
    const bool up = (lane & off) != 0;
#pragma unroll
    for (int k = 0; k < off; ++k) {
      const float lo = v[k], hi = v[k + off];
      v[k] = up ? hi : lo; v[k + off] = up ? lo : hi;
    }
#pragma unroll
    for (int k = 0; k < off; ++k) v[k] += __shfl_xor_sync(0xffffffffu, v[k + off], off);
  }
  return v[0];
}

struct Bars {
  // leader-only: TMA transactions of both CTAs (dy, Ws, Wab), gate arrivals (8 warps per CTA), d_xn reads (12 warps per CTA)
  uint64_t dy_full, ws_full, wab_full[NATOM], g_full[2], dxn_empty, g_stored[2];
  // both CTAs (the leader's multicast commits)
  uint64_t ws_empty, wab_empty[NATOM], dh_full[2], gfree[2], dxn_full;
  // local
  uint64_t ab_full, ab_read, x_full, dy_free, dh_issued, g_loc[2];
  uint32_t tmem;
};

// maps: dy, x, dx [M][D] (box 64 x 64); ws^T [H][D] (box 64 x 32); wa, wb [H][D] (box 64 x 64); a, b [M][H] (box 64 x 64)
// dab [M][2H] (dA | dB, bf16); part [grid][2D] fp32 (dgamma | dbeta partials)
extern "C" __global__ void __launch_bounds__(512, 1)
transition_bwd_d384_sm100(const __grid_constant__ CUtensorMap mdy, const __grid_constant__ CUtensorMap mx,
                          const __grid_constant__ CUtensorMap mwst, const __grid_constant__ CUtensorMap mwa,
                          const __grid_constant__ CUtensorMap mwb, const __grid_constant__ CUtensorMap ma,
                          const __grid_constant__ CUtensorMap mb, const __grid_constant__ CUtensorMap mdx,
                          const float* __restrict__ rstd, const float* __restrict__ c1, const float* __restrict__ gamma,
                          __nv_bfloat16* __restrict__ dab, float* __restrict__ part, int tiles) {
  extern __shared__ __align__(1024) uint8_t sm[];
  const uint32_t su = smem_u32(sm);
  Bars& B = *reinterpret_cast<Bars*>(sm + O_BAR);
  const int tid = threadIdx.x, warp = tid >> 5, lane = tid & 31;
  const int cta = blockIdx.x, G = gridDim.x;
  const int crank = (int)cluster_rank();
  const bool leader = crank == 0;
  auto count = [&](int k) { return (tiles > k) ? (tiles - k + G - 1) / G : 0; };
  const int n_valid = count(cta), n_local = count(cta & ~1);
  const int nch = n_local * NCH;
  auto tile_of = [&](int i) { return i < n_valid ? cta + i * G : (n_valid > 0 ? cta + (n_valid - 1) * G : 0); };

  if (tid == 0) {
    mbar_init(&B.dy_full, 1); mbar_init(&B.ws_full, 1);
    for (int s = 0; s < NATOM; ++s) { mbar_init(&B.wab_full[s], 1); mbar_init(&B.wab_empty[s], 1); }
    mbar_init(&B.dxn_empty, 24);
    mbar_init(&B.ws_empty, 1); mbar_init(&B.dxn_full, 1);
    for (int s = 0; s < 2; ++s) {
      mbar_init(&B.g_full[s], 16); mbar_init(&B.dh_full[s], 1); mbar_init(&B.gfree[s], 1);
      mbar_init(&B.g_stored[s], 8); mbar_init(&B.g_loc[s], 8);
    }
    mbar_init(&B.ab_full, 1); mbar_init(&B.ab_read, 8); mbar_init(&B.x_full, 1); mbar_init(&B.dy_free, 1); mbar_init(&B.dh_issued, 1);
    fence_barrier_init();
    prefetch_map(&mdy); prefetch_map(&mx); prefetch_map(&mwst); prefetch_map(&mwa); prefetch_map(&mwb);
    prefetch_map(&ma); prefetch_map(&mb); prefetch_map(&mdx);
  }
  if (tid < D_) reinterpret_cast<float*>(sm + O_GB)[tid] = gamma[tid];
  if (warp == 2) { tmem_alloc2(smem_u32(&B.tmem), 512); tmem_relinquish2(); }
  tc_fence_before();
  __syncthreads();
  cluster_sync_relaxed();
  tc_fence_after();
  const uint32_t tmem = B.tmem;

  if (warp < 4) setmaxnreg_dec<56>();
  if (warp == 0) {
    // ------------------------------------------------------------------------------------------ dy (the pair's, on the leader's
    // barrier), every chunk's a and b (this CTA's), and once the tile's products are done its x over the weight / a-b region
    if (lane == 0) {
      // a / b of chunk c + 2 and the next tile's x and dy go to L2 ahead of their loads: with one a / b slot the load of chunk
      // c + 1 starts only once the gate has read chunk c, and from HBM its latency was the chunk period's largest part
      auto pf_ab = [&](int c) {
        if (c >= nch) return;
        const int i2 = c / NCH, j2 = c % NCH, r2 = tile_of(i2) * ROWS;
#pragma unroll
        for (int h = 0; h < 2; ++h) { tma_prefetch_2d(&ma, j2 * HS, r2 + h * 64); tma_prefetch_2d(&mb, j2 * HS, r2 + h * 64); }
      };
      auto pf_tile = [&](const CUtensorMap* m, int i2) {
        if (i2 >= n_local) return;
        const int r2 = tile_of(i2) * ROWS;
#pragma unroll
        for (int cb = 0; cb < NKB; ++cb)
#pragma unroll
          for (int h = 0; h < 2; ++h) tma_prefetch_2d(m, cb * 64, r2 + h * 64);
      };
      pf_ab(0); pf_ab(1);
      for (int i = 0; i < n_local; ++i) {
        const int row0 = tile_of(i) * ROWS;
        if (i >= 1) mbar_wait(&B.dy_free, (i - 1) & 1);        // the last tile's dx is stored and its x read
        if (leader) mbar_expect_tx(&B.dy_full, 2 * TILE);
#pragma unroll
        for (int cb = 0; cb < NKB; ++cb)
#pragma unroll
          for (int h = 0; h < 2; ++h) tma_load_2d_2sm(su + O_DY + cb * KBT + h * 8192, &mdy, &B.dy_full, cb * 64, row0 + h * 64);
        pf_tile(&mx, i);
        pf_tile(&mdy, i + 1);
        for (int j = 0; j < NCH; ++j) {
          const int c = i * NCH + j;
          if (c >= 1) mbar_wait(&B.ab_read, (c - 1) & 1);
          pf_ab(c + 2);
          mbar_expect_tx(&B.ab_full, 2 * KBT);
#pragma unroll
          for (int h = 0; h < 2; ++h) {
            tma_load_2d(su + O_AB + h * 8192, &ma, &B.ab_full, j * HS, row0 + h * 64);
            tma_load_2d(su + O_AB + KBT + h * 8192, &mb, &B.ab_full, j * HS, row0 + h * 64);
          }
        }
        mbar_wait(&B.dxn_full, i & 1);
        mbar_expect_tx(&B.x_full, TILE);
#pragma unroll
        for (int cb = 0; cb < NKB; ++cb)
#pragma unroll
          for (int h = 0; h < 2; ++h) tma_load_2d(su + O_X + cb * KBT + h * 8192, &mx, &B.x_full, cb * 64, row0 + h * 64);
      }
    }
  } else if (warp == 3) {
    // ------------------------------------------------------------------------------------------ weights: this CTA's half of every
    // chunk's Ws^T (early: dh_c) and [Wa_c; Wb_c] (late: d_xn_c), on the leader's barriers. Ws_{c+1} goes out before Wab_c (it is
    // released by dh_c, long before Wab_{c-1} by d_xn_{c-1}), except at a tile boundary, where the next tile's Ws waits for the region
    if (lane == 0) {
      auto load_ws = [&](int c) {
        const int i = c / NCH, j = c % NCH;
        if (c >= 1) mbar_wait(&B.ws_empty, (c - 1) & 1);
        if (j == 0 && i >= 1) mbar_wait(&B.dy_free, (i - 1) & 1);
        if (leader) mbar_expect_tx(&B.ws_full, 2 * WS_SLOT);
#pragma unroll
        for (int kb = 0; kb < NKB; ++kb) tma_load_2d_2sm(su + O_WS + kb * WSK, &mwst, &B.ws_full, kb * 64, j * HS + crank * 32);
      };
      auto load_wab = [&](int c) {                            // the chunk's three atoms, each on its own ring slot
        const int j = c % NCH;
#pragma unroll
        for (int a3 = 0; a3 < 3; ++a3) {
          const int k = c * 3 + a3, s = k % NATOM;
          if (k >= NATOM) mbar_wait(&B.wab_empty[s], ((k / NATOM) - 1) & 1);
          if (leader) mbar_expect_tx(&B.wab_full[s], 2 * WAB_ATOM);
          const int d0 = a3 * 128 + crank * 64;
          tma_load_2d_2sm(su + O_WAB + s * WAB_ATOM, &mwa, &B.wab_full[s], d0, j * HS);
          tma_load_2d_2sm(su + O_WAB + s * WAB_ATOM + 8192, &mwb, &B.wab_full[s], d0, j * HS);
        }
      };
      for (int t = 0; t <= nch; ++t) {
        if (t < nch && t >= NCH && t % NCH == 0) { load_wab(t - 1); load_ws(t); continue; }
        if (t < nch) load_ws(t);
        if (t >= 1) load_wab(t - 1);
      }
    }
  } else if (warp == 1 || warp == 2) {
    if (leader) {
      if (warp == 1) {
        // ---------------------------------------------------------------------------------------- dh_c = dy Ws_c
        const uint64_t ad0 = desc_k128(su + O_DY), bd0 = desc_k128(su + O_WS);
        for (int c = 0; c < nch; ++c) {
          const int i = c / NCH, j = c % NCH, s = c & 1;
          if (j == 0) mbar_wait(&B.dy_full, i & 1);
          mbar_wait(&B.ws_full, c & 1);
          if (c >= 2) {                                        // d_xn_{c-2} and the dA / dB stores have read [dA | dB] from this buffer
            mbar_wait(&B.gfree[s], ((c >> 1) - 1) & 1);
            mbar_wait_cl(&B.g_stored[s], ((c >> 1) - 1) & 1);
          }
          tc_fence_after();
          if (elect_one()) {
#pragma unroll
            for (int kb = 0; kb < NKB; ++kb)
#pragma unroll
              for (int ks = 0; ks < 4; ++ks)
                umma_ss2(tmem + T_DH + s * 64, ad0 + (uint64_t)(((kb * KBT) >> 4) + ks * 2), bd0 + (uint64_t)(((kb * WSK) >> 4) + ks * 2),
                         I_DH, (kb > 0 || ks > 0) ? 1u : 0u);
            tc_commit2_mc(&B.ws_empty, 3);
            tc_commit2_mc(&B.dh_full[s], 3);
          }
          __syncwarp();
          if (lane == 0) mbar_arrive(&B.dh_issued);
        }
      } else {
        // ---------------------------------------------------------------------------------------- d_xn += [dA | dB]_c [Wa_c; Wb_c]
        const uint64_t bw0 = desc_mn128(su + O_WAB, WAB_ATOM);
        for (int q = 0; q < nch; ++q) {
          const int i = q / NCH, j = q % NCH, s = q & 1;
          mbar_wait_cl(&B.g_full[s], (q >> 1) & 1);
          if (j == 0 && i >= 1) mbar_wait_cl(&B.dxn_empty, (i - 1) & 1);
          // tensor-pipe order dh_{q+1} before d_xn_q (within a tile): dh_{q+2} can only follow d_xn_q (it overwrites [dA | dB]_q), so
          // letting d_xn_{q+1} in first put the gate's whole latency into every other chunk's critical path
          if (j + 1 < NCH) mbar_wait(&B.dh_issued, (q + 1) & 1);
#pragma unroll
          for (int a3 = 0; a3 < 3; ++a3) {
            const int k = q * 3 + a3, sl = k % NATOM;
            mbar_wait(&B.wab_full[sl], (k / NATOM) & 1);
            tc_fence_after();
            const uint64_t bd = bw0 + (uint64_t)((sl * WAB_ATOM) >> 4);
            if (elect_one()) {
#pragma unroll
              for (int ks = 0; ks < 8; ++ks)
                umma_ts2(tmem + T_DXN + a3 * 128, tmem + T_DH + s * 64 + ks * 8, bd + (uint64_t)((kRowBlk[ks] * 2048) >> 4), I_DX,
                         (j > 0 || ks > 0) ? 1u : 0u);
              tc_commit2_mc(&B.wab_empty[sl], 3);
              if (a3 == 2) {
                tc_commit2_mc(&B.gfree[s], 3);
                if (j == NCH - 1) tc_commit2_mc(&B.dxn_full, 3);
              }
            }
            __syncwarp();
          }
        }
      }
    }
  } else {
    setmaxnreg_inc<152>();
    const uint32_t lb = (uint32_t)(warp & 3) * 32, trow = tmem + (lb << 16);
    const int r = (int)lb + lane;
    const int hf = (tid - 128) >> 7;                           // the third of the columns this thread takes in the LayerNorm backward
    float accg[4] = {0.f, 0.f, 0.f, 0.f}, accb[4] = {0.f, 0.f, 0.f, 0.f};
    // -------------------------------------------------------------------------------------------- LayerNorm backward + residual of tile i
    auto lnb = [&](int i) {
      const bool real = i < n_valid;
      const int grow = tile_of(i) * ROWS + r;
      float* ex = reinterpret_cast<float*>(sm + O_EX);
      const uint32_t gam_u = su + O_GB + hf * 128 * 4;
      mbar_wait(&B.dxn_full, i & 1);
      tc_fence_after();
      const float rs = rstd[grow], mean = c1[grow] / rs;
      mbar_wait(&B.x_full, i & 1);
      const uint32_t xb = su + O_X + hf * 2 * KBT, dyb = su + O_DY + hf * 2 * KBT, tcol = trow + T_DXN + hf * 128;
      const f2 RS = mk2(rs, rs), NMR = mk2(-mean * rs, -mean * rs);
      // d_xn is read from TMEM 32 columns at a time in both passes (rounded to bf16 the same way each time): holding the third's 64
      // bf16 pairs in registers across the passes spilled (128-register compile)
      auto dxn32 = [&](int g, uint32_t (&dn)[16]) {
        uint32_t v[32];
        tmem_ld32(tcol + g * 32, v);
        tmem_wait_ld();
#pragma unroll
        for (int k = 0; k < 16; ++k) dn[k] = pack_bf16(__uint_as_float(v[2 * k]), __uint_as_float(v[2 * k + 1]));
      };
      f2 pa2[2] = {mk2(0.f, 0.f), mk2(0.f, 0.f)}, pb2[2] = {mk2(0.f, 0.f), mk2(0.f, 0.f)};
#pragma unroll 1
      for (int g = 0; g < 4; ++g) {
        uint32_t dn[16];
        dxn32(g, dn);
        float work[32];
#pragma unroll
        for (int qq = 0; qq < 4; ++qq) {
          const uint4 xv = lds128_nv(xb + (g >> 1) * KBT + sw128(r, (g & 1) * 4 + qq));
          const uint32_t xw[4] = {xv.x, xv.y, xv.z, xv.w};
#pragma unroll
          for (int kk = 0; kk < 4; ++kk) {
            const int e = qq * 4 + kk, pr = g * 16 + e;       // column pair within this third
            const uint32_t n = dn[e];
            const f2 N = mk2(bf16lo(n), bf16hi(n));
            const f2 XH = fma2(mk2(bf16lo(xw[kk]), bf16hi(xw[kk])), RS, NMR);
            const float2 gg = lds64f_nv(gam_u + pr * 8);
            const f2 W = mul2(mk2(gg.x, gg.y), N);
            pa2[kk & 1] = fma2(XH, W, pa2[kk & 1]); pb2[kk & 1] = add2(pb2[kk & 1], W);
            const f2 NX = mul2(N, XH);
            work[2 * e] = lo2(NX); work[2 * e + 1] = hi2(NX);
          }
        }
        const float sg = reduce_scatter32(work, lane);
        if (real) accg[g] += sg;
#pragma unroll
        for (int e = 0; e < 16; ++e) { const uint32_t n = dn[e]; work[2 * e] = bf16lo(n); work[2 * e + 1] = bf16hi(n); }
        const float sb = reduce_scatter32(work, lane);
        if (real) accb[g] += sb;
      }
      const f2 PA = add2(pa2[0], pa2[1]), PB = add2(pb2[0], pb2[1]);
      ex[hf * ROWS + r] = lo2(PA) + hi2(PA);
      ex[(3 + hf) * ROWS + r] = lo2(PB) + hi2(PB);
      named_bar_sync(1, 384);
      const float ca = ((ex[r] + ex[ROWS + r]) + ex[2 * ROWS + r]) * (1.f / D_);
      const float cbv = ((ex[3 * ROWS + r] + ex[4 * ROWS + r]) + ex[5 * ROWS + r]) * (1.f / D_);
      const f2 NCA = mk2(-ca, -ca), NCB = mk2(-cbv, -cbv);
#pragma unroll 1
      for (int g = 0; g < 4; ++g) {
        uint32_t dn[16];
        dxn32(g, dn);
#pragma unroll
        for (int qq = 0; qq < 4; ++qq) {
          const uint32_t off = (g >> 1) * KBT + sw128(r, (g & 1) * 4 + qq);
          const uint4 xv = lds128(xb + off), dv = lds128(dyb + off);
          const uint32_t xw[4] = {xv.x, xv.y, xv.z, xv.w}, dw[4] = {dv.x, dv.y, dv.z, dv.w};
          uint32_t o[4];
#pragma unroll
          for (int k = 0; k < 4; ++k) {
            const int e = qq * 4 + k, pr = g * 16 + e;
            const uint32_t n = dn[e];
            const f2 XH = fma2(mk2(bf16lo(xw[k]), bf16hi(xw[k])), RS, NMR);
            const float2 gg = lds64f(gam_u + pr * 8);
            const f2 W = mul2(mk2(gg.x, gg.y), mk2(bf16lo(n), bf16hi(n)));
            const f2 T = mul2(fma2(XH, NCA, add2(W, NCB)), RS);        // bf16((w - xhat ca - cb) rstd) + dy
            const uint32_t t = pack_bf16(lo2(T), hi2(T));
            o[k] = pack_bf16(bf16lo(t) + bf16lo(dw[k]), bf16hi(t) + bf16hi(dw[k]));
          }
          sts128(dyb + off, make_uint4(o[0], o[1], o[2], o[3]));    // dx over dy, in place
        }
      }
      tc_fence_before();
      __syncwarp();
      if (lane == 0) mbar_arrive_remote_relaxed(&B.dxn_empty, 0);
      fence_proxy_async();
      named_bar_sync(1, 384);
      if (tid == 128) {
        if (real) {
          const int row0 = tile_of(i) * ROWS;
#pragma unroll
          for (int cb = 0; cb < NKB; ++cb)
#pragma unroll
            for (int h = 0; h < 2; ++h) tma_store_2d(&mdx, su + O_DY + cb * KBT + h * 8192, cb * 64, row0 + h * 64);
          tma_store_commit();
          tma_store_wait_read0();
        }
        mbar_arrive(&B.dy_free);
      }
    };
    if (warp < 8 || warp >= 12) {
      // ------------------------------------------------------------------------------------------ gate: warpgroup g takes units
      // 32 g .. 32 g + 31 of every chunk; the tile's LayerNorm backward follows its last chunk
      const int g = warp >= 12 ? 1 : 0;
      for (int c = 0; c < nch; ++c) {
        const int i = c / NCH, j = c % NCH, s = c & 1;
        mbar_wait(&B.dh_full[s], (c >> 1) & 1);
        mbar_wait(&B.ab_full, c & 1);
        tc_fence_after();
        uint32_t dh[32];
        tmem_ld32(trow + T_DH + s * 64 + g * 32, dh);
        uint4 av[4], bv[4];
#pragma unroll
        for (int q = 0; q < 4; ++q) { av[q] = lds128(su + O_AB + sw128(r, g * 4 + q)); bv[q] = lds128(su + O_AB + KBT + sw128(r, g * 4 + q)); }
        tmem_wait_ld();
        __syncwarp();
        if (lane == 0) mbar_arrive(&B.ab_read);
        uint32_t da[16], db[16];
#pragma unroll
        for (int k = 0; k < 16; ++k) {
          const uint32_t aw = k % 4 == 0 ? av[k / 4].x : k % 4 == 1 ? av[k / 4].y : k % 4 == 2 ? av[k / 4].z : av[k / 4].w;
          const uint32_t bw = k % 4 == 0 ? bv[k / 4].x : k % 4 == 1 ? bv[k / 4].y : k % 4 == 2 ? bv[k / 4].z : bv[k / 4].w;
          gate_pair(dh[2 * k], dh[2 * k + 1], aw, bw, da[k], db[k]);
        }
        tmem_st16(trow + T_DH + s * 64 + g * 32, da);
        tmem_st16(trow + T_DH + s * 64 + g * 32 + 16, db);
        tmem_wait_st();
        tc_fence_before();
        __syncwarp();
        if (lane == 0) { mbar_arrive_remote_relaxed(&B.g_full[s], 0); mbar_arrive(&B.g_loc[s]); }
        if (j == NCH - 1) lnb(i);
      }
    } else {
      // ------------------------------------------------------------------------------------------ warps 8-11: dA / dB of every chunk
      // from TMEM to global memory (quad-transposed: each store writes 8 rows x 64 B), then the tile's LayerNorm backward; the
      // row-per-thread stores kept the gate warps ~2 k clk per chunk (measured)
      auto store_t = [&](size_t base, const uint32_t* v) {
        const int k4 = lane & 3;
        uint4 x[4] = {make_uint4(v[0], v[1], v[2], v[3]), make_uint4(v[4], v[5], v[6], v[7]),
                      make_uint4(v[8], v[9], v[10], v[11]), make_uint4(v[12], v[13], v[14], v[15])};
#pragma unroll
        for (int p = 0; p < 2; ++p) {
          const bool od = k4 & 1;
          uint4 t = od ? x[2 * p] : x[2 * p + 1];
          t.x = __shfl_xor_sync(0xffffffffu, t.x, 1); t.y = __shfl_xor_sync(0xffffffffu, t.y, 1);
          t.z = __shfl_xor_sync(0xffffffffu, t.z, 1); t.w = __shfl_xor_sync(0xffffffffu, t.w, 1);
          if (od) x[2 * p] = t; else x[2 * p + 1] = t;
        }
#pragma unroll
        for (int p = 0; p < 2; ++p) {
          const bool hi = k4 & 2;
          uint4 t = hi ? x[p] : x[p + 2];
          t.x = __shfl_xor_sync(0xffffffffu, t.x, 2); t.y = __shfl_xor_sync(0xffffffffu, t.y, 2);
          t.z = __shfl_xor_sync(0xffffffffu, t.z, 2); t.w = __shfl_xor_sync(0xffffffffu, t.w, 2);
          if (hi) x[p] = t; else x[p + 2] = t;
        }
#pragma unroll
        for (int t = 0; t < 4; ++t) stg128(dab + base + (size_t)t * (2 * H_), x[t]);
      };
      for (int c = 0; c < nch; ++c) {
        const int i = c / NCH, j = c % NCH, s = c & 1;
        mbar_wait(&B.g_loc[s], (c >> 1) & 1);
        tc_fence_after();
        uint32_t v[64];                                        // [dA 0..31 | dB 0..31 | dA 32..63 | dB 32..63], bf16 pairs
        tmem_ld32(trow + T_DH + s * 64, *reinterpret_cast<uint32_t(*)[32]>(v));
        tmem_ld32(trow + T_DH + s * 64 + 32, *reinterpret_cast<uint32_t(*)[32]>(v + 32));
        tmem_wait_ld();
        tc_fence_before();
        __syncwarp();
        if (lane == 0) mbar_arrive_remote_relaxed(&B.g_stored[s], 0);
        if (i < n_valid) {
          const size_t base = (size_t)(tile_of(i) * ROWS + lb + (lane & ~3)) * (2 * H_) + j * HS + (lane & 3) * 8;
          store_t(base, v);
          store_t(base + H_, v + 16);
          store_t(base + 32, v + 32);
          store_t(base + H_ + 32, v + 48);
        }
        if (j == NCH - 1) lnb(i);
      }
    }
    // dgamma / dbeta: lane l of the warp (lane quadrant qd, third hf) holds columns hf 128 + 32 g + l, summed over its 32 rows of
    // every tile; the four quadrants are added in a fixed order
    float* red = reinterpret_cast<float*>(sm + O_RED);
    const int qd = warp & 3;
#pragma unroll
    for (int g = 0; g < 4; ++g) {
      red[qd * 2 * D_ + hf * 128 + g * 32 + lane] = accg[g];
      red[qd * 2 * D_ + D_ + hf * 128 + g * 32 + lane] = accb[g];
    }
    named_bar_sync(1, 384);
    for (int col = tid - 128; col < 2 * D_; col += 384)
      part[(size_t)cta * 2 * D_ + col] = (red[col] + red[2 * D_ + col]) + (red[4 * D_ + col] + red[6 * D_ + col]);
  }
  tc_fence_before();
  __syncthreads();
  cluster_sync_relaxed();
  if (warp == 2) { tc_fence_after(); tmem_dealloc2(tmem, 512); }
}

// dgamma | dbeta = sum over the CTAs' partials, in a fixed order (4 interleaved row groups, then those)
extern "C" __global__ void __launch_bounds__(256) transition_bwd_d384_reduce(const float* __restrict__ part, float* __restrict__ dgb,
                                                                            int nblk) {
  __shared__ float s4[4][64];
  const int t = threadIdx.x & 63, rg = threadIdx.x >> 6, col = blockIdx.x * 64 + t;
  float v = 0.f;
  for (int k = rg; k < nblk; k += 4) v += part[(size_t)k * 2 * D_ + col];
  s4[rg][t] = v;
  __syncthreads();
  if (threadIdx.x < 64) dgb[col] = (s4[0][t] + s4[1][t]) + (s4[2][t] + s4[3][t]);
}

// ================================================================================== wiring surface
// Built into a cubin by the newest nvcc that knows sm_100a and launched through the driver API from `transition_sm100.cu`;
// the dynamic shared-memory size the launch must request is exported here so the host never restates it.
extern "C" __device__ int transition_smem_bytes = SMEM_BYTES;
