// tbwd_d64.cu (research source: experiments/transition_fused_sm100/src/tbwd_d64.cu, branch perf/transition-sm100-b200; generated by export_engine.py)
// — the Transition backward at D = 64, H = 4D = 256, bf16, as ONE fused sm_100a kernel plus a partial-sum reduction: the
// two-role design of tbwd.cu (same contract and rounding points) with what D = 64 changes. SPDX-License-Identifier: Apache-2.0
//
//   dh = bf16(dy Ws)      a = xn Wa^T, b = xn Wb^T (fp32)      sig = rcp(1 + ex2(-a log2 e))      silu = a sig
//   h  = bf16(silu b)     dA = bf16((dh b)(sig + silu(1 - sig)))      dB = bf16(dh silu)
//   dWs = dy^T h, dWa = dA^T xn, dWb = dB^T xn (fp32 sums, rounded once)      d_xn = bf16(dA Wa + dB Wb)
//   dx = bf16(bf16((w - xhat ca - cb) rstd) + dy), w = gamma d_xn;  dgamma += d_xn xhat, dbeta += d_xn
//
// DW CTAs (4 hidden slices of 64 units x R replicas; a 2-CTA cluster = two slices of one replica, which multicast each tile's xn / dy):
//   recompute dh / a / b of their slice, run the gate into shared memory, accumulate [dWa_s; dWb_s] (M 128, N 64) and dWs_s (M 64,
//   run as M 128 with the MN-major A descriptor's second 64-row block aliased onto the first: rows 64..127 duplicate 0..63 and are
//   dropped) in tensor memory.
// DX CTAs (one 128-row tile at a time): ALL weights resident (96 KB, loaded once; no ring, no pairing), per 64-unit chunk dh_j and
//   [a|b]_j into tensor memory, the gate writes [dA|dB]_j back over [a|b]_j, d_xn accumulates with an A-from-TMEM product over the
//   packed [Wa_j; Wb_j] tile (MN-major B); then the LayerNorm backward + residual (fp32x2) from tensor memory.
#include "sm100.cuh"
using namespace s100;

#define REG_LOW 56
#define REG_GATE 152
#define REG_EPI 152

#ifndef HID
#define HID 256                                                // hidden units (n x D); n = 4 by default
#endif
constexpr int D_ = 64, H_ = HID, HS = 64, NSL = H_ / HS, ROWS = 128;
constexpr int KB = 16384;                                      // one K-block: [128 rows][64 bf16], 128-B swizzled
constexpr int INB = 2 * KB, IN_XN = KB;                        // an input stage: dy | xn
// ---- DW role shared memory: Ws_s [64 d][64 hs] | [Wa_s; Wb_s] [128][64 d] | 2 input stages | h | dA dB
constexpr int W_WS = 0, W_WAB = 8192, W_IN = W_WAB + KB;
constexpr int W_H = W_IN + 2 * INB, W_DAB = W_H + KB, W_BAR = W_DAB + 2 * KB;
// ---- DX role shared memory: Ws_j x 4 | [Wa_j; Wb_j] x 4 | 2 input stages (xn half reloaded with x for the LayerNorm backward) | gamma
constexpr int X_WS = 0, X_WAB = NSL * 8192, X_IN = X_WAB + NSL * KB;
constexpr int X_GAM = X_IN + 2 * INB, X_BAR = X_GAM + 512;
constexpr int SMEM_BYTES = (W_BAR > X_BAR ? W_BAR : X_BAR) + 512;
static_assert(SMEM_BYTES <= 232448, "shared memory budget");
static_assert(HID != 256 || SMEM_BYTES == 164864, "bench_wbwd.py BSMEM[64]");
static_assert(W_WAB % 1024 == 0 && W_IN % 1024 == 0 && X_WAB % 1024 == 0 && X_IN % 1024 == 0, "1 KB alignment of swizzled tiles");
constexpr int KSD = D_ / 16;                                   // K16 steps over D (K-major, one K-block)
constexpr int KSR = ROWS / 16;                                 // K16 steps over a tile's rows / a chunk's 128 [dA | dB] columns

constexpr int CL = 2;
constexpr uint16_t CL_MASK = (1u << CL) - 1;
constexpr uint32_t I_DH = idesc_bf16(128, 64, 0, 1), I_AB = idesc_bf16(128, 128), I_DXN = idesc_bf16(128, D_, 0, 1);
constexpr uint32_t I_DWAB = idesc_bf16(128, D_, 1, 1), I_DWS = idesc_bf16(128, 64, 1, 1);

struct Par {
  const CUtensorMap *dy, *xn, *x, *ws, *wa, *wb, *dx;
  const float *rstd, *c1, *gamma;
  float *partab, *parts, *dgbw;
  int tiles, ndw;
};
struct BarsW { uint64_t w_full, xn_full[2], dy_full[2], xn_empty[2], dy_empty[2], dhab_full, gate_read, g_full, g_empty, wg_done; uint32_t tmem; };
struct BarsX {
  uint64_t w_full, in_full[2], in_empty[2], x_full[2], xn_dead[2], abdh_full[2], g_full[2], ab_free[2], dxn_full, dxn_empty;
  uint32_t tmem;
};

// the 16-row block of the packed [Wa_j; Wb_j] tile matching A-operand block ks of the half-by-half [dA | dB] layout
__device__ constexpr int kRowBlk[8] = {0, 1, 4, 5, 2, 3, 6, 7};
// tbwd.cu's fp32x2 gate: h = l b, dA = (g b) fma(l, 1 - s, s), dB = g l, with l = a s and the kit sigmoid per unit
DEVI void gate_pair16(uint32_t dh0, uint32_t dh1, uint32_t a0, uint32_t a1, uint32_t b0, uint32_t b1, uint32_t& hp, uint32_t& dap, uint32_t& dbp) {
  const uint32_t gp = pack_bf16(__uint_as_float(dh0), __uint_as_float(dh1));
  const f2 G = mk2(bf16lo(gp), bf16hi(gp)), A = mk2u(a0, a1), Bv = mk2u(b0, b1);
  const f2 S = mk2(sigmoid_kit(__uint_as_float(a0)), sigmoid_kit(__uint_as_float(a1)));
  const f2 L = mul2(A, S);
  const f2 H = mul2(L, Bv), DB = mul2(G, L);
  const f2 U = fma2(L, fma2(S, mk2(-1.f, -1.f), mk2(1.f, 1.f)), S);
  const f2 DA = mul2(mul2(G, Bv), U);
  hp = pack_bf16(lo2(H), hi2(H)); dap = pack_bf16(lo2(DA), hi2(DA)); dbp = pack_bf16(lo2(DB), hi2(DB));
}

// ================================================================================================ DW role
DEVI void weight_role(const Par& p, uint8_t* sm, int cta, int warp, int lane) {
  const uint32_t su = smem_u32(sm);
  BarsW& B = *reinterpret_cast<BarsW*>(sm + W_BAR);
  const int slice = cta % NSL, repl = cta / NSL, R = p.ndw / NSL;
  const int crank = (int)cluster_rank();                   // == slice % CL
  const int n_local = (p.tiles > repl) ? (p.tiles - repl + R - 1) / R : 0;
  constexpr uint32_t T_DH = 0, T_AB = 64, T_DWAB = 256, T_DWS = 384;
  const uint32_t tid = threadIdx.x;
  if (tid == 0) {
    mbar_init(&B.w_full, 1);
    for (int s = 0; s < 2; ++s) {
      mbar_init(&B.xn_full[s], 1); mbar_init(&B.dy_full[s], 1); mbar_init(&B.xn_empty[s], CL); mbar_init(&B.dy_empty[s], CL);
    }
    mbar_init(&B.dhab_full, 1); mbar_init(&B.gate_read, 8); mbar_init(&B.wg_done, 1);
    mbar_init(&B.g_full, 8); mbar_init(&B.g_empty, 1);
    fence_barrier_init();
  }
  if (warp == 2) { tmem_alloc(smem_u32(&B.tmem), 512); tmem_relinquish(); }
  tc_fence_before();
  __syncthreads();
  cluster_sync_relaxed();
  tc_fence_after();
  const uint32_t tmem = B.tmem;

  if (warp == 0) {
    if (lane == 0) {
      mbar_expect_tx(&B.w_full, 8192 + KB);
      tma_load_2d(su + W_WS, p.ws, &B.w_full, slice * HS, 0);
      tma_load_2d(su + W_WAB, p.wa, &B.w_full, 0, slice * HS);
      tma_load_2d(su + W_WAB + 8192, p.wb, &B.w_full, 0, slice * HS);
      // xn first (freed first, by the dWab product), then dy (freed by dWs); the two slices of the cluster each request one of the
      // two 8 KB boxes of each half and multicast it
      for (int i = 0; i < n_local; ++i) {
        const int b = i & 1, row = (repl + i * R) * ROWS;
        const uint32_t dst = su + W_IN + b * INB;
#pragma unroll
        for (int src = 1; src >= 0; --src) {
          uint64_t* full = src ? &B.xn_full[b] : &B.dy_full[b];
          if (i >= 2) mbar_wait(src ? &B.xn_empty[b] : &B.dy_empty[b], ((i >> 1) - 1) & 1);
          mbar_expect_tx(full, KB);
          tma_load_2d_mc(dst + src * IN_XN + crank * 8192, src ? p.xn : p.dy, full, 0, row + crank * 64, CL_MASK);
        }
      }
    }
  } else if (warp == 1) {
    // dh and [a|b] of each tile
    mbar_wait(&B.w_full, 0);
    const uint64_t dws = desc_mn128(su + W_WS, KB), dwab = desc_k128(su + W_WAB);
    for (int i = 0; i < n_local; ++i) {
      const int b = i & 1;
      mbar_wait(&B.xn_full[b], (i >> 1) & 1);
      if (i >= 1) mbar_wait(&B.gate_read, (i - 1) & 1);
      tc_fence_after();
      const uint64_t ddy = desc_k128(su + W_IN + b * INB), dxn = desc_k128(su + W_IN + b * INB + IN_XN);
      if (elect_one()) {
#pragma unroll
        for (int ks = 0; ks < KSD; ++ks) umma_ss(tmem + T_AB, dxn + (uint64_t)(ks * 2), dwab + (uint64_t)(ks * 2), I_AB, ks > 0 ? 1u : 0u);
      }
      __syncwarp();
      mbar_wait(&B.dy_full[b], (i >> 1) & 1);
      tc_fence_after();
      if (elect_one()) {
#pragma unroll
        for (int ks = 0; ks < KSD; ++ks)
          umma_ss(tmem + T_DH, ddy + (uint64_t)(ks * 2), dws + (uint64_t)(ks * 2048 >> 4), I_DH, ks > 0 ? 1u : 0u);
        tc_commit(&B.dhab_full);
      }
      __syncwarp();
    }
  } else if (warp == 2) {
    // the weight gradients of each tile
    const uint64_t ddab = desc_mn128(su + W_DAB, KB), dh_ = desc_mn128(su + W_H, KB);
    for (int k = 0; k < n_local; ++k) {
      const int b = k & 1;
      mbar_wait(&B.g_full, k & 1);
      tc_fence_after();
      // dWs: A = dy^T (M = d); the second 64-row M block aliases the first (LBO 0), so accumulator rows 64..127 repeat 0..63
      const uint64_t ddy = desc_mn128(su + W_IN + b * INB, 0), dxn = desc_mn128(su + W_IN + b * INB + IN_XN, KB);
      if (elect_one()) {
#pragma unroll
        for (int ks = 0; ks < KSR; ++ks)       // [dWa_s; dWb_s] += [dA | dB]^T xn    (K = the tile's 128 rows)
          umma_ss(tmem + T_DWAB, ddab + (uint64_t)(ks * 2048 >> 4), dxn + (uint64_t)(ks * 2048 >> 4), I_DWAB, (k > 0 || ks > 0) ? 1u : 0u);
        tc_commit_mc(&B.xn_empty[b], CL_MASK);
#pragma unroll
        for (int ks = 0; ks < KSR; ++ks)       // dWs_s += dy^T h
          umma_ss(tmem + T_DWS, ddy + (uint64_t)(ks * 2048 >> 4), dh_ + (uint64_t)(ks * 2048 >> 4), I_DWS, (k > 0 || ks > 0) ? 1u : 0u);
        tc_commit(&B.g_empty);
        tc_commit_mc(&B.dy_empty[b], CL_MASK);
        if (k == n_local - 1) tc_commit(&B.wg_done);
      }
      __syncwarp();
    }
    if (n_local == 0 && elect_one()) mbar_arrive(&B.wg_done);
    __syncwarp();
  } else if ((warp >= 4 && warp < 8) || warp >= 12) {
    // gate, split by columns over two warpgroups: warps 4-7 hidden units 0..31 of the slice, warps 12-15 units 32..63
    setmaxnreg_inc<REG_GATE>();
    const uint32_t lb = (uint32_t)(warp & 3) * 32, r = lb + lane, trow = tmem + (lb << 16);
    const int half = warp >= 12 ? 1 : 0;
    for (int i = 0; i < n_local; ++i) {
      mbar_wait(&B.dhab_full, i & 1);
      tc_fence_after();
      if (i >= 1) mbar_wait(&B.g_empty, (i - 1) & 1);
      uint32_t dh[32], av[32], bv[32];
      tmem_ld32(trow + T_DH + half * 32, dh);
      tmem_ld32(trow + T_AB + half * 32, av);
      tmem_ld32(trow + T_AB + 64 + half * 32, bv);
      tmem_wait_ld();
      tc_fence_before(); __syncwarp(); if (lane == 0) mbar_arrive(&B.gate_read);
#pragma unroll
      for (int qq = 0; qq < 4; ++qq) {                     // 8 hidden units -> one 16-byte chunk of h, dA and dB each
        uint32_t hp[4], dap[4], dbp[4];
#pragma unroll
        for (int kk = 0; kk < 4; ++kk) {
          const int k = qq * 4 + kk;
          gate_pair16(dh[2 * k], dh[2 * k + 1], av[2 * k], av[2 * k + 1], bv[2 * k], bv[2 * k + 1], hp[kk], dap[kk], dbp[kk]);
        }
        const uint32_t off = sw128(r, half * 4 + qq);
        sts128(su + W_H + off, make_uint4(hp[0], hp[1], hp[2], hp[3]));
        sts128(su + W_DAB + off, make_uint4(dap[0], dap[1], dap[2], dap[3]));
        sts128(su + W_DAB + KB + off, make_uint4(dbp[0], dbp[1], dbp[2], dbp[3]));
      }
      fence_proxy_async();
      __syncwarp();
      if (lane == 0) mbar_arrive(&B.g_full);
    }
  } else if (warp >= 8) {
    // the CTA's fp32 partials: [dWa_s; dWb_s] rows (a / b unit) = TMEM lanes 0..127; dWs_s rows (d) = lanes 0..63
    setmaxnreg_inc<REG_EPI>();
    const uint32_t lb = (uint32_t)(warp & 3) * 32, r = lb + lane, trow = tmem + (lb << 16);
    mbar_wait(&B.wg_done, 0);
    tc_fence_after();
    float* pab = p.partab + ((size_t)cta * 128 + r) * D_;
    float* ps = p.parts + ((size_t)cta * D_ + (r & (D_ - 1))) * HS;
#pragma unroll
    for (int cc = 0; cc < 4; ++cc) {
      const bool dws = cc >= 2;
      uint32_t v[32];
      if (n_local > 0) {
        tmem_ld32(trow + (dws ? T_DWS + (cc - 2) * 32 : T_DWAB + cc * 32), v);   // warp-collective: every lane loads
        tmem_wait_ld();
      } else {                                             // fewer tiles than replicas: this CTA accumulated nothing, its partial is 0
#pragma unroll
        for (int k = 0; k < 32; ++k) v[k] = 0u;
      }
      if (dws && r >= (uint32_t)D_) continue;              // the duplicated dWs rows
      float* dst = dws ? ps + (cc - 2) * 32 : pab + cc * 32;
#pragma unroll
      for (int k = 0; k < 8; ++k) *reinterpret_cast<uint4*>(dst + 4 * k) = make_uint4(v[4 * k], v[4 * k + 1], v[4 * k + 2], v[4 * k + 3]);
    }
  }
  tc_fence_before();
  __syncthreads();
  cluster_sync_relaxed();
  if (warp == 2) { tc_fence_after(); tmem_dealloc(tmem, 512); }
}

// warp reduce-scatter: lane l returns the sum over the warp of v[l]
DEVI float reduce_scatter32(float (&v)[32], int lane) {
#pragma unroll
  for (int off = 16; off; off >>= 1) {
    const bool up = (lane & off) != 0;
#pragma unroll
    for (int k = 0; k < off; ++k) {
      const float lo = v[k], hi = v[k + off];
      v[k] = up ? hi : lo; v[k + off] = up ? lo : hi;
    }
#pragma unroll
    for (int k = 0; k < off; ++k) v[k] += __shfl_xor_sync(0xffffffffu, v[k + off], off);
  }
  return v[0];
}

// ================================================================================================ DX role
DEVI void input_role(const Par& p, uint8_t* sm, int cta, int ndx, int warp, int lane) {
  const uint32_t su = smem_u32(sm);
  BarsX& B = *reinterpret_cast<BarsX*>(sm + X_BAR);
  const int n_local = (p.tiles > cta) ? (p.tiles - cta + ndx - 1) / ndx : 0;
  const int nch = n_local * NSL;
  auto tile_of = [&](int i) { return cta + i * ndx; };
  constexpr uint32_t T_AB = 0, T_DH = 256, T_DXN = 384;          // AB x2 (128 each; [dA|dB] is written back over its first 64), DH x2
  const uint32_t tid = threadIdx.x;
  if (tid == 0) {
    mbar_init(&B.w_full, 1);
    for (int s = 0; s < 2; ++s) {
      mbar_init(&B.in_full[s], 1); mbar_init(&B.in_empty[s], 1); mbar_init(&B.x_full[s], 1); mbar_init(&B.xn_dead[s], 1);
      mbar_init(&B.abdh_full[s], 1); mbar_init(&B.g_full[s], 8); mbar_init(&B.ab_free[s], 1);
    }
    mbar_init(&B.dxn_full, 1); mbar_init(&B.dxn_empty, 4);
    fence_barrier_init();
  }
  if (tid < D_) reinterpret_cast<float*>(sm + X_GAM)[tid] = p.gamma[tid];
  if (warp == 2) { tmem_alloc(smem_u32(&B.tmem), 512); tmem_relinquish(); }
  tc_fence_before();
  __syncthreads();
  cluster_sync_relaxed();
  tc_fence_after();
  const uint32_t tmem = B.tmem;

  if (warp == 0) {
    if (lane == 0) {
      auto issue_in = [&](int i) {
        const int b = i & 1, row = tile_of(i) * ROWS;
        if (i >= 2) mbar_wait(&B.in_empty[b], ((i >> 1) - 1) & 1);
        mbar_expect_tx(&B.in_full[b], INB);
        const uint32_t dst = su + X_IN + b * INB;
#pragma unroll
        for (int h = 0; h < 2; ++h) {
          tma_load_2d(dst + h * 8192, p.dy, &B.in_full[b], 0, row + h * 64);
          tma_load_2d(dst + IN_XN + h * 8192, p.xn, &B.in_full[b], 0, row + h * 64);
        }
      };
      auto issue_x = [&](int i) {                         // the tile's xn is dead: reload that half with x for the epilogue
        const int b = i & 1, row = tile_of(i) * ROWS;
        mbar_wait(&B.xn_dead[b], (i >> 1) & 1);
        mbar_expect_tx(&B.x_full[b], KB);
        const uint32_t dst = su + X_IN + b * INB + IN_XN;
#pragma unroll
        for (int h = 0; h < 2; ++h) tma_load_2d(dst + h * 8192, p.x, &B.x_full[b], 0, row + h * 64);
      };
      for (int i = 0; i <= n_local; ++i) {
        if (i < n_local) issue_in(i);
        if (i >= 1) issue_x(i - 1);
      }
    }
  } else if (warp == 3) {
    if (lane == 0 && n_local > 0) {                      // all weights, once
      mbar_expect_tx(&B.w_full, NSL * (8192 + KB));
#pragma unroll
      for (int j = 0; j < NSL; ++j) {
        tma_load_2d(su + X_WS + j * 8192, p.ws, &B.w_full, j * HS, 0);
        tma_load_2d(su + X_WAB + j * KB, p.wa, &B.w_full, 0, j * HS);
        tma_load_2d(su + X_WAB + j * KB + 8192, p.wb, &B.w_full, 0, j * HS);
      }
    }
  } else if (warp == 1) {
    // dh_j and [a|b]_j
    if (n_local > 0) mbar_wait(&B.w_full, 0);
    for (int c = 0; c < nch; ++c) {
      const int i = c / NSL, j = c % NSL, s = c & 1, u = c >> 1;
      if (j == 0) mbar_wait(&B.in_full[i & 1], (i >> 1) & 1);
      if (c >= 2) mbar_wait(&B.ab_free[s], (u - 1) & 1);
      tc_fence_after();
      const uint64_t ddy = desc_k128(su + X_IN + (i & 1) * INB), dxn = desc_k128(su + X_IN + (i & 1) * INB + IN_XN);
      const uint64_t dws = desc_mn128(su + X_WS + j * 8192, KB), dwab = desc_k128(su + X_WAB + j * KB);
      if (elect_one()) {
#pragma unroll
        for (int ks = 0; ks < KSD; ++ks)
          umma_ss(tmem + T_DH + s * 64, ddy + (uint64_t)(ks * 2), dws + (uint64_t)(ks * 2048 >> 4), I_DH, ks > 0 ? 1u : 0u);
#pragma unroll
        for (int ks = 0; ks < KSD; ++ks)
          umma_ss(tmem + T_AB + s * 128, dxn + (uint64_t)(ks * 2), dwab + (uint64_t)(ks * 2), I_AB, ks > 0 ? 1u : 0u);
        tc_commit(&B.abdh_full[s]);
        if (j == NSL - 1) tc_commit(&B.xn_dead[i & 1]);
      }
      __syncwarp();
    }
  } else if (warp == 2) {
    // d_xn += [dA | dB] [Wa_j; Wb_j]  (A from TMEM)
    for (int q = 0; q < nch; ++q) {
      const int i = q / NSL, j = q % NSL, s = q & 1, u = q >> 1;
      mbar_wait(&B.g_full[s], u & 1);
      if (j == 0 && i >= 1) mbar_wait(&B.dxn_empty, (i - 1) & 1);
      tc_fence_after();
      const uint64_t dwab = desc_mn128(su + X_WAB + j * KB, KB);
      if (elect_one()) {
#pragma unroll
        for (int ks = 0; ks < KSR; ++ks)
          umma_ts(tmem + T_DXN, tmem + T_AB + s * 128 + ks * 8, dwab + (uint64_t)(kRowBlk[ks] * 2048 >> 4), I_DXN, (j > 0 || ks > 0) ? 1u : 0u);
        tc_commit(&B.ab_free[s]);
        if (j == NSL - 1) tc_commit(&B.dxn_full);
      }
      __syncwarp();
    }
  } else if ((warp >= 4 && warp < 8) || warp >= 12) {
    // gate: [dA | dB] back into TMEM, half by half (dA(0-31) | dB(0-31) | dA(32-63) | dB(32-63)), each warpgroup one half of the units
    const uint32_t lb = (uint32_t)(warp & 3) * 32, trow = tmem + (lb << 16);
    setmaxnreg_inc<REG_GATE>();
    const int half = warp >= 12 ? 1 : 0;
    for (int c = 0; c < nch; ++c) {
      const int s = c & 1, u = c >> 1;
      mbar_wait(&B.abdh_full[s], u & 1);
      tc_fence_after();
      uint32_t dh[32], av[32], bv[32];
      tmem_ld32(trow + T_DH + s * 64 + half * 32, dh);
      tmem_ld32(trow + T_AB + s * 128 + half * 32, av);
      tmem_ld32(trow + T_AB + s * 128 + 64 + half * 32, bv);
      tmem_wait_ld();
      uint32_t da[16], db[16];
#pragma unroll
      for (int k = 0; k < 16; ++k) { uint32_t hh; gate_pair16(dh[2 * k], dh[2 * k + 1], av[2 * k], av[2 * k + 1], bv[2 * k], bv[2 * k + 1], hh, da[k], db[k]); (void)hh; }
      tmem_st16(trow + T_AB + s * 128 + half * 32, da);
      tmem_st16(trow + T_AB + s * 128 + half * 32 + 16, db);
      tmem_wait_st();
      tc_fence_before();
      __syncwarp();
      if (lane == 0) mbar_arrive(&B.g_full[s]);
    }
  } else if (warp >= 8) {
    // ------------------------------------------------------------------------------------ LayerNorm backward + residual (fp32x2)
    setmaxnreg_inc<REG_EPI>();
    const int t2 = (int)tid - 256;
    const uint32_t lb = (uint32_t)(warp & 3) * 32, r = lb + lane, trow = tmem + (lb << 16);
    const uint32_t gam_u = su + X_GAM;
    float accg[2] = {0.f, 0.f}, accb[2] = {0.f, 0.f};
    for (int i = 0; i < n_local; ++i) {
      const int b = i & 1, grow = tile_of(i) * ROWS + (int)r;
      mbar_wait(&B.dxn_full, i & 1);
      tc_fence_after();
      uint32_t dn[32];                                     // d_xn rounded once to bf16
#pragma unroll
      for (int cc = 0; cc < 2; ++cc) {
        uint32_t v[32];
        tmem_ld32(trow + T_DXN + cc * 32, v);
        tmem_wait_ld();
#pragma unroll
        for (int k = 0; k < 16; ++k) dn[cc * 16 + k] = pack_bf16(__uint_as_float(v[2 * k]), __uint_as_float(v[2 * k + 1]));
      }
      tc_fence_before();
      __syncwarp();
      if (lane == 0) mbar_arrive(&B.dxn_empty);
      const float rs = p.rstd[grow], mean = p.c1[grow] / rs;
      mbar_wait(&B.x_full[b], (i >> 1) & 1);
      const uint32_t dyb = su + X_IN + b * INB, xb = dyb + IN_XN;
      const f2 RS = mk2(rs, rs), NMR = mk2(-mean * rs, -mean * rs);
      f2 pa2[2] = {mk2(0.f, 0.f), mk2(0.f, 0.f)}, pb2[2] = {mk2(0.f, 0.f), mk2(0.f, 0.f)};
#pragma unroll
      for (int g = 0; g < 2; ++g) {
        float work[32];
#pragma unroll
        for (int qq = 0; qq < 4; ++qq) {
          const uint4 xv = lds128_nv(xb + sw128(r, g * 4 + qq));
          const uint32_t xw[4] = {xv.x, xv.y, xv.z, xv.w};
#pragma unroll
          for (int kk = 0; kk < 4; ++kk) {
            const int e = qq * 4 + kk, pr = g * 16 + e;     // column pair
            const uint32_t n = dn[pr];
            const f2 N = mk2(bf16lo(n), bf16hi(n));
            const f2 XH = fma2(mk2(bf16lo(xw[kk]), bf16hi(xw[kk])), RS, NMR);
            const float2 gg = lds64f_nv(gam_u + pr * 8);
            const f2 W = mul2(mk2(gg.x, gg.y), N);
            pa2[kk & 1] = fma2(XH, W, pa2[kk & 1]); pb2[kk & 1] = add2(pb2[kk & 1], W);
            const f2 NX = mul2(N, XH);
            work[2 * e] = lo2(NX); work[2 * e + 1] = hi2(NX);
          }
        }
        accg[g] += reduce_scatter32(work, lane);
#pragma unroll
        for (int e = 0; e < 16; ++e) { const uint32_t n = dn[g * 16 + e]; work[2 * e] = bf16lo(n); work[2 * e + 1] = bf16hi(n); }
        accb[g] += reduce_scatter32(work, lane);
      }
      const f2 PA = add2(pa2[0], pa2[1]), PB = add2(pb2[0], pb2[1]);
      const float ca = (lo2(PA) + hi2(PA)) * (1.f / D_), cbv = (lo2(PB) + hi2(PB)) * (1.f / D_);
      const f2 NCA = mk2(-ca, -ca), NCB = mk2(-cbv, -cbv);
#pragma unroll
      for (int q = 0; q < 8; ++q) {
        const uint32_t off = sw128(r, q);
        const uint4 xv = lds128(xb + off), dv = lds128(dyb + off);
        const uint32_t xw[4] = {xv.x, xv.y, xv.z, xv.w}, dw[4] = {dv.x, dv.y, dv.z, dv.w};
        uint32_t o[4];
#pragma unroll
        for (int k = 0; k < 4; ++k) {
          const int pr = q * 4 + k;
          const uint32_t n = dn[pr];
          const f2 XH = fma2(mk2(bf16lo(xw[k]), bf16hi(xw[k])), RS, NMR);
          const float2 gg = lds64f(gam_u + pr * 8);
          const f2 W = mul2(mk2(gg.x, gg.y), mk2(bf16lo(n), bf16hi(n)));
          const f2 T = mul2(fma2(XH, NCA, add2(W, NCB)), RS);        // bf16((w - xhat ca - cb) rstd) + dy
          const uint32_t t = pack_bf16(lo2(T), hi2(T));
          o[k] = pack_bf16(bf16lo(t) + bf16lo(dw[k]), bf16hi(t) + bf16hi(dw[k]));
        }
        sts128(dyb + off, make_uint4(o[0], o[1], o[2], o[3]));
      }
      fence_proxy_async();
      named_bar_sync(1, 128);
      if (t2 == 0) {
        const int row0 = tile_of(i) * ROWS;
#pragma unroll
        for (int h = 0; h < 2; ++h) tma_store_2d(p.dx, dyb + h * 8192, 0, row0 + h * 64);
        tma_store_commit();
        tma_store_wait_read0();
        mbar_arrive(&B.in_empty[b]);
      }
    }
    float* row = p.dgbw + ((size_t)cta * 4 + (warp & 3)) * (2 * D_);
#pragma unroll
    for (int g = 0; g < 2; ++g) { row[g * 32 + lane] = accg[g]; row[D_ + g * 32 + lane] = accb[g]; }
    if (t2 == 0) tma_store_wait0();
  }
  tc_fence_before();
  __syncthreads();
  cluster_sync_relaxed();
  if (warp == 2) { tc_fence_after(); tmem_dealloc(tmem, 512); }
}

extern "C" __global__ void __launch_bounds__(512, 1)
transition_bwd_d64_sm100(const __grid_constant__ CUtensorMap mdy, const __grid_constant__ CUtensorMap mxn, const __grid_constant__ CUtensorMap mx,
                         const __grid_constant__ CUtensorMap mws, const __grid_constant__ CUtensorMap mwa, const __grid_constant__ CUtensorMap mwb,
                         const __grid_constant__ CUtensorMap mdx, const float* __restrict__ rstd, const float* __restrict__ c1,
                         const float* __restrict__ gamma, float* __restrict__ partab, float* __restrict__ parts, float* __restrict__ dgbw,
                         int tiles, int ndw) {
  const Par p{&mdy, &mxn, &mx, &mws, &mwa, &mwb, &mdx, rstd, c1, gamma, partab, parts, dgbw, tiles, ndw};
  extern __shared__ __align__(1024) uint8_t sm[];
  const int warp = threadIdx.x >> 5, lane = threadIdx.x & 31;
  if (warp < 4) setmaxnreg_dec<REG_LOW>();
  if ((int)blockIdx.x < ndw) weight_role(p, sm, blockIdx.x, warp, lane);
  else input_role(p, sm, blockIdx.x - ndw, gridDim.x - ndw, warp, lane);
}

// partab [NDW][128][64] (rows 0..63 dWa_s, 64..127 dWb_s), parts [NDW][64 d][64 hs] -> bf16 dWa, dWb [256][64], dWs [64][256];
// dgbw [NDX * 4][128] -> dgamma, dbeta (fp32). Fixed summation order: a replay is bit-identical.
extern "C" __global__ void transition_bwd_d64_reduce(const float* __restrict__ partab, const float* __restrict__ parts, const float* __restrict__ dgbw,
                                                     float* __restrict__ dwa, float* __restrict__ dwb, float* __restrict__ dws,
                                                     float* __restrict__ dgam, float* __restrict__ dbeta, int ndw, int nrows_dg) {
  const int idx = blockIdx.x * blockDim.x + threadIdx.x, R = ndw / NSL;
  if (idx < 2 * H_ * D_) {                                  // dWa / dWb element: (which, slice, hs, d)
    const int which = idx / (H_ * D_), rem = idx % (H_ * D_), slice = rem / (HS * D_), hs = (rem / D_) % HS, d = rem % D_;
    float v = 0.f;
    for (int rr = 0; rr < R; ++rr) v += partab[((size_t)(rr * NSL + slice) * 128 + which * 64 + hs) * D_ + d];
    (which == 0 ? dwa : dwb)[(slice * HS + hs) * D_ + d] = v;
  } else if (idx < 3 * H_ * D_) {                           // dWs element (d, slice, hs)
    const int rem = idx - 2 * H_ * D_, d = rem / H_, hh = rem % H_, slice = hh / HS, hs = hh % HS;
    float v = 0.f;
    for (int rr = 0; rr < R; ++rr) v += parts[((size_t)(rr * NSL + slice) * D_ + d) * HS + hs];
    dws[d * H_ + hh] = v;
  } else if (idx < 3 * H_ * D_ + 2 * D_) {
    const int c = idx - 3 * H_ * D_;
    float v = 0.f;
    for (int rr = 0; rr < nrows_dg; ++rr) v += dgbw[(size_t)rr * (2 * D_) + c];
    (c < D_ ? dgam : dbeta)[c % D_] = v;
  }
}

// ================================================================================== wiring surface
// Built into a cubin by the newest nvcc that knows sm_100a and launched through the driver API from `transition_sm100.cu`;
// the dynamic shared-memory size the launch must request is exported here so the host never restates it.
extern "C" __device__ int transition_smem_bytes = SMEM_BYTES;
