// tfwd_d256.cu (research source: experiments/transition_fused_sm100/src/tfwd_d256.cu, branch perf/transition-sm100-b200; generated by export_engine.py)
// — the Transition forward at D = 256, H = 4D = 1024, bf16, as ONE fused sm_100a kernel with 2-CTA tcgen05.mma (the
// tfwd2.cu scheme: the two CTAs of a cluster run their own 128-row tiles in lockstep, the leader issues M = 256 products whose B operand
// is split by N across the pair). What D = 256 changes:
//   * tensor memory is full: the output accumulator is 256 columns and the two [a|b] buffers 2 x 128, so h_j is written back IN PLACE
//     over the first 32 columns of its own [a|b] buffer, and expand(j + 2) waits for squeeze(j) (not for the SwiGLU's read)
//   * shared memory is full: one xn buffer and one x buffer (64 KB each) plus a 2-stage weight ring (48 KB per stage and CTA:
//     Wa_j or Wb_j [64 n][256 k] = 32 KB, Ws_j rows d = 128 crank .. +127 [128 d][64 k] = 16 KB). The next tile's x is loaded INTO the xn
//     buffer as soon as the current tile's last expand is done and normalised there in place; the x buffer holds the tile's own x for the
//     residual and the output staging.
//   * expand   [a|b]_j = xn [Wa_j; Wb_j]^T   M 256, N 128, K 256 (four 128-B-swizzled K-blocks)
//     squeeze  acc    += h_j Ws_j^T          M 256, N 256 (128 per CTA), K 64, A = h_j from tensor memory
// Rounding points as tfwd2.cu: xn bf16, a / b fp32, h = bf16(silu(a) b) (kit sigmoid), acc fp32, out = bf16(x + acc).
// SPDX-License-Identifier: Apache-2.0
#include "sm100.cuh"
using namespace s100;

#ifndef HID
#define HID 1024                                                // hidden units (n x D); n = 4 by default
#endif
constexpr int D_ = 256, H_ = HID, HS = 64, NCH = H_ / HS, ROWS = 128, NKB = D_ / 64;
static_assert((NCH & (NCH - 1)) == 0 && NCH >= 2, "power-of-two chunk count");
constexpr int NW = 2;                                          // weight ring depth (both rings)
constexpr int WAB_SLOT = NKB * 8192, WS_SLOT = (D_ / 2) * 128;   // [64 n][256 k] as 4 K-blocks of 8 KB; Ws [128 d][64 k]
constexpr int TILE = ROWS * D_ * 2;                            // 64 KB: four K-blocks of 128 rows
constexpr int KBT = ROWS * 128;                                // one K-block of a tile: 16 KB
constexpr int O_WAB = 0, O_WS = NW * WAB_SLOT;
constexpr int O_X = O_WS + NW * WS_SLOT;
constexpr int O_XN = O_X + TILE;
constexpr int O_GB = O_XN + TILE;
constexpr int O_BAR = O_GB + 2 * D_ * 4;
constexpr int SMEM_BYTES = O_BAR + 512;
static_assert(SMEM_BYTES <= 232448, "shared memory budget");
static_assert(HID != 1024 || SMEM_BYTES == 231936, "bench_w.py SMEM[256]");
constexpr int KS_EX = D_ / 16, KS_SQ = HS / 16;
constexpr uint32_t T_AB = 0, T_OUT = 256;                      // AB x2 (128 each; h_j in place over its first 32), OUT 256
constexpr uint32_t IDESC_EX = idesc_bf16(256, 128), IDESC_SQ = idesc_bf16(256, D_);

#define SIGF(a) sigmoid_kit(a)

struct Bars {
  // leader-only: weight fulls (both CTAs' transactions), xn_full (2 LN arrivals), h_full / out_empty (4 warps per CTA)
  uint64_t wab_full[NW], ws_full[NW], xn_full, h_full[2], out_empty;
  // both CTAs (leader's multicast commits)
  uint64_t wab_empty[NW], ws_empty[NW], xn_empty, ex_done[2], sq_done[2], out_full;
  // local
  uint64_t xl_full, x_full, x_empty;
  uint32_t tmem;
};

extern "C" __global__ void __launch_bounds__(512, 1)
transition_fwd_d256_sm100(const __grid_constant__ CUtensorMap mx, const __grid_constant__ CUtensorMap mwa,
                          const __grid_constant__ CUtensorMap mwb, const __grid_constant__ CUtensorMap mws,
                          const __grid_constant__ CUtensorMap mout, const __grid_constant__ CUtensorMap mxn,
                          const float* __restrict__ gamma, const float* __restrict__ beta, float* __restrict__ rstd,
                          float* __restrict__ c1, int tiles, float eps, int save) {
  extern __shared__ __align__(1024) uint8_t sm[];
  const uint32_t su = smem_u32(sm);
  Bars& B = *reinterpret_cast<Bars*>(sm + O_BAR);
  const int tid = threadIdx.x, warp = tid >> 5, lane = tid & 31;
  const int cta = blockIdx.x, G = gridDim.x;
  const int crank = (int)cluster_rank();
  const bool leader = crank == 0;
  auto count = [&](int k) { return (tiles > k) ? (tiles - k + G - 1) / G : 0; };
  const int n_valid = count(cta), n_local = count(cta & ~1);
  const int nch = n_local * NCH;
  auto tile_of = [&](int i) { return i < n_valid ? cta + i * G : (n_valid > 0 ? cta + (n_valid - 1) * G : 0); };

  if (tid == 0) {
    for (int s = 0; s < NW; ++s) {
      mbar_init(&B.wab_full[s], 1); mbar_init(&B.ws_full[s], 1); mbar_init(&B.wab_empty[s], 1); mbar_init(&B.ws_empty[s], 1);
    }
    for (int s = 0; s < 2; ++s) { mbar_init(&B.h_full[s], 8); mbar_init(&B.ex_done[s], 1); mbar_init(&B.sq_done[s], 1); }
    mbar_init(&B.xn_full, 2); mbar_init(&B.xn_empty, 1); mbar_init(&B.out_empty, 8); mbar_init(&B.out_full, 1);
    mbar_init(&B.xl_full, 1); mbar_init(&B.x_full, 1); mbar_init(&B.x_empty, 1);
    fence_barrier_init();
    prefetch_map(&mx); prefetch_map(&mwa); prefetch_map(&mwb); prefetch_map(&mws); prefetch_map(&mout); prefetch_map(&mxn);
  }
  if (tid < D_) { reinterpret_cast<float*>(sm + O_GB)[tid] = gamma[tid]; reinterpret_cast<float*>(sm + O_GB)[D_ + tid] = beta[tid]; }
  if (warp == 2) { tmem_alloc2(smem_u32(&B.tmem), 512); tmem_relinquish2(); }
  tc_fence_before();
  __syncthreads();
  cluster_sync_relaxed();                                      // the barriers were published by fence_barrier_init
  tc_fence_after();
  const uint32_t tmem = B.tmem;

  auto load_tile = [&](uint32_t dst, uint64_t* bar, int row) {
    mbar_expect_tx(bar, TILE);
#pragma unroll
    for (int cb = 0; cb < NKB; ++cb)
#pragma unroll
      for (int h = 0; h < 2; ++h) tma_load_2d(dst + cb * KBT + h * 8192, &mx, bar, cb * 64, row + h * 64);
  };

  if (warp < 4) setmaxnreg_dec<56>();
  if (warp == 0) {
    // ------------------------------------------------------------------------------------------ x producer: x(i) into the xn buffer (for
    // the LayerNorm, once xn(i - 1) is dead) and into the x buffer (for the residual, once the epilogue of tile i - 1 has stored)
    if (lane == 0) {
      for (int i = 0; i < n_local; ++i) {
        const int row = tile_of(i) * ROWS;
        if (i >= 1) mbar_wait(&B.xn_empty, (i - 1) & 1);
        load_tile(su + O_XN, &B.xl_full, row);
        if (i >= 1) mbar_wait(&B.x_empty, (i - 1) & 1);
        load_tile(su + O_X, &B.x_full, row);
      }
    }
  } else if (warp == 3) {
    // ------------------------------------------------------------------------------------------ weight producer: this CTA's half of
    // every chunk; transactions complete on the leader's barriers, armed with the pair's total bytes
    if (lane == 0) {
      const CUtensorMap* mab = leader ? &mwa : &mwb;
      int ca = 0, cs = 0;
      while (ca < nch || cs < nch) {
        if (ca < nch && (ca < NW || mbar_test(&B.wab_empty[ca % NW], ((ca / NW) - 1) & 1))) {
          const int s = ca % NW, j = ca & (NCH - 1);
          if (leader) mbar_expect_tx(&B.wab_full[s], 2 * WAB_SLOT);
          const uint32_t slot = su + O_WAB + s * WAB_SLOT;
#pragma unroll
          for (int kb = 0; kb < NKB; ++kb) tma_load_2d_2sm(slot + kb * 8192, mab, &B.wab_full[s], kb * 64, j * HS);
          ++ca;
        }
        if (cs < nch && (cs < NW || mbar_test(&B.ws_empty[cs % NW], ((cs / NW) - 1) & 1))) {
          const int s = cs % NW, j = cs & (NCH - 1);
          if (leader) mbar_expect_tx(&B.ws_full[s], 2 * WS_SLOT);
          tma_load_2d_2sm(su + O_WS + s * WS_SLOT, &mws, &B.ws_full[s], j * HS, crank * (D_ / 2));
          ++cs;
        }
      }
    }
  } else if (warp == 1 || warp == 2) {
    // ------------------------------------------------------------------------------------------ MMA issue: leader only; warp 1 expands,
    // warp 2 squeezes
    if (leader) {
      if (warp == 1) {
        for (int c = 0; c < nch; ++c) {
          const int i = c / NCH, j = c & (NCH - 1), s = c & 1, u = c >> 1, sw = c % NW;
          if (j == 0) mbar_wait_cl(&B.xn_full, i & 1);
          mbar_wait(&B.wab_full[sw], (c / NW) & 1);
          if (c >= 2) mbar_wait(&B.sq_done[s], (u - 1) & 1);   // h_{c-2} (in this buffer) has been consumed
          tc_fence_after();
          const uint64_t ad = desc_k128(su + O_XN), bd = desc_k128(su + O_WAB + sw * WAB_SLOT);
          if (elect_one()) {
#pragma unroll
            for (int ks = 0; ks < KS_EX; ++ks)
              umma_ss2(tmem + T_AB + s * 128, ad + (uint64_t)(((ks >> 2) * KBT + (ks & 3) * 32) >> 4),
                       bd + (uint64_t)(((ks >> 2) * 8192 + (ks & 3) * 32) >> 4), IDESC_EX, ks > 0 ? 1u : 0u);
            tc_commit2_mc(&B.ex_done[s], 3);
            tc_commit2_mc(&B.wab_empty[sw], 3);
            if (j == NCH - 1) tc_commit2_mc(&B.xn_empty, 3);
          }
          __syncwarp();
        }
      } else {
        for (int q = 0; q < nch; ++q) {
          const int i = q / NCH, j = q & (NCH - 1), s = q & 1, u = q >> 1, sw = q % NW;
          mbar_wait(&B.ws_full[sw], (q / NW) & 1);
          mbar_wait_cl(&B.h_full[s], u & 1);
          if (j == 0 && i >= 1) mbar_wait_cl(&B.out_empty, (i - 1) & 1);
          tc_fence_after();
          const uint64_t bd = desc_k128(su + O_WS + sw * WS_SLOT);
          if (elect_one()) {
#pragma unroll
            for (int ks = 0; ks < KS_SQ; ++ks)
              umma_ts2(tmem + T_OUT, tmem + T_AB + s * 128 + ks * 8, bd + (uint64_t)(ks * 2), IDESC_SQ, (j > 0 || ks > 0) ? 1u : 0u);
            tc_commit2_mc(&B.sq_done[s], 3);
            tc_commit2_mc(&B.ws_empty[sw], 3);
            if (j == NCH - 1) tc_commit2_mc(&B.out_full, 3);
          }
          __syncwarp();
        }
      }
    }
  } else if ((warp >= 4 && warp < 8) || warp >= 12) {
    // ------------------------------------------------------------------------------------------ SwiGLU: two warpgroups alternate chunks,
    // four 16-column steps with the next step's TMEM loads in flight; h_j is stored over the first 32 columns of its own buffer
    setmaxnreg_inc<152>();
    const uint32_t lb = (uint32_t)(warp & 3) * 32, trow = tmem + (lb << 16);
    for (int c = (warp >= 12 ? 1 : 0); c < nch; c += 2) {
      const int s = c & 1, u = c >> 1;
      mbar_wait(&B.ex_done[s], u & 1);
      tc_fence_after();
      uint32_t hp[32];
      {
        uint32_t a[2][16], b[2][16];
        tmem_ld16(trow + T_AB + s * 128, a[0]);
        tmem_ld16(trow + T_AB + s * 128 + 64, b[0]);
        tmem_wait_ld();
#pragma unroll
        for (int q = 0; q < 4; ++q) {
          if (q < 3) {
            tmem_ld16(trow + T_AB + s * 128 + (q + 1) * 16, a[(q + 1) & 1]);
            tmem_ld16(trow + T_AB + s * 128 + 64 + (q + 1) * 16, b[(q + 1) & 1]);
          }
#pragma unroll
          for (int k = 0; k < 8; ++k) {
            const float a0 = __uint_as_float(a[q & 1][2 * k]), a1 = __uint_as_float(a[q & 1][2 * k + 1]);
            const float b0 = __uint_as_float(b[q & 1][2 * k]), b1 = __uint_as_float(b[q & 1][2 * k + 1]);
            hp[q * 8 + k] = pack_bf16(a0 * SIGF(a0) * b0, a1 * SIGF(a1) * b1);
          }
          if (q < 3) tmem_wait_ld();
        }
      }
      uint32_t h0[16], h1[16];
#pragma unroll
      for (int k = 0; k < 16; ++k) { h0[k] = hp[k]; h1[k] = hp[16 + k]; }
      tmem_st16(trow + T_AB + s * 128, h0);
      tmem_st16(trow + T_AB + s * 128 + 16, h1);
      tmem_wait_st();
      tc_fence_before();
      __syncwarp();
      if (lane == 0) mbar_arrive_remote_relaxed(&B.h_full[s], 0);
    }
  } else if (warp >= 8) {
    // ------------------------------------------------------------------------------------------ LayerNorm (in place in the xn buffer) and
    // the residual epilogue, one row per thread
    setmaxnreg_inc<152>();
    const int t2 = tid - 256;
    const uint32_t lb = (uint32_t)(warp & 3) * 32, r = lb + lane, trow = tmem + (lb << 16);
    const uint32_t gb_u = su + O_GB;
    auto ln = [&](int i) {
      const int grow = tile_of(i) * ROWS + (int)r;
      const bool real = i < n_valid;
      mbar_wait(&B.xl_full, i & 1);
      if (t2 == 0) tma_store_wait_read0();                 // the previous tile's xn store has read the buffer
      named_bar_sync(1, 128);
      const uint32_t xnb = su + O_XN;
      float sum[4] = {0.f, 0.f, 0.f, 0.f};
#pragma unroll 4
      for (int cq = 0; cq < 8 * NKB; ++cq) {                // 8 columns at a time
        const uint4 t = lds128(xnb + (cq >> 3) * KBT + sw128(r, cq & 7));
        const uint32_t w[4] = {t.x, t.y, t.z, t.w};
#pragma unroll
        for (int k = 0; k < 4; ++k) sum[k] += bf16lo(w[k]) + bf16hi(w[k]);
      }
      const float mean = ((sum[0] + sum[1]) + (sum[2] + sum[3])) * (1.f / D_);
      float sq[4] = {0.f, 0.f, 0.f, 0.f};
#pragma unroll 4
      for (int cq = 0; cq < 8 * NKB; ++cq) {
        const uint4 t = lds128(xnb + (cq >> 3) * KBT + sw128(r, cq & 7));
        const uint32_t w[4] = {t.x, t.y, t.z, t.w};
#pragma unroll
        for (int k = 0; k < 4; ++k) { const float d0 = bf16lo(w[k]) - mean, d1 = bf16hi(w[k]) - mean; sq[k] += d0 * d0 + d1 * d1; }
      }
      const float rs = rsqrtf(((sq[0] + sq[1]) + (sq[2] + sq[3])) * (1.f / D_) + eps);
#pragma unroll 4
      for (int cq = 0; cq < 8 * NKB; ++cq) {
        const uint32_t ad = xnb + (cq >> 3) * KBT + sw128(r, cq & 7);
        const uint4 t = lds128(ad);
        const uint32_t w[4] = {t.x, t.y, t.z, t.w};
        uint32_t o[4];
#pragma unroll
        for (int k = 0; k < 4; ++k) {
          const int col = cq * 8 + 2 * k;
          const float2 g2 = lds64f(gb_u + col * 4), b2 = lds64f(gb_u + D_ * 4 + col * 4);
          o[k] = pack_bf16((bf16lo(w[k]) - mean) * rs * g2.x + b2.x, (bf16hi(w[k]) - mean) * rs * g2.y + b2.y);
        }
        sts128(ad, make_uint4(o[0], o[1], o[2], o[3]));
      }
      if (save && real) { rstd[grow] = rs; c1[grow] = mean * rs; }
      fence_proxy_async();
      named_bar_sync(1, 128);
      if (t2 == 0) {
        mbar_arrive_remote_cta(&B.xn_full, 0);
        if (save && real) {
          const int row0 = tile_of(i) * ROWS;
#pragma unroll
          for (int cb = 0; cb < NKB; ++cb)
#pragma unroll
            for (int h = 0; h < 2; ++h) tma_store_2d(&mxn, xnb + cb * KBT + h * 8192, cb * 64, row0 + h * 64);
          tma_store_commit();
          tma_store_wait_read0();                          // the loader refills this buffer once xn is dead: the store must have read it
        }
      }
    };
    auto epi = [&](int i) {
      mbar_wait(&B.out_full, i & 1);
      mbar_wait(&B.x_full, i & 1);
      tc_fence_after();
      const uint32_t xb = su + O_X;
#pragma unroll 1
      for (int cc = 0; cc < D_ / 32; ++cc) {
        uint32_t acc[32];
        tmem_ld32(trow + T_OUT + cc * 32, acc);
        tmem_wait_ld();
        const int cb = cc >> 1;
#pragma unroll
        for (int qq = 0; qq < 4; ++qq) {
          const int q = (cc & 1) * 4 + qq;
          const uint32_t ad = xb + cb * KBT + sw128(r, q);
          const uint4 xv = lds128(ad);
          const uint32_t xw[4] = {xv.x, xv.y, xv.z, xv.w};
          uint32_t o[4];
#pragma unroll
          for (int k = 0; k < 4; ++k)
            o[k] = pack_bf16(bf16lo(xw[k]) + __uint_as_float(acc[qq * 8 + 2 * k]), bf16hi(xw[k]) + __uint_as_float(acc[qq * 8 + 2 * k + 1]));
          sts128(ad, make_uint4(o[0], o[1], o[2], o[3]));
        }
      }
      tc_fence_before();
      __syncwarp();
      if (lane == 0) mbar_arrive_remote_relaxed(&B.out_empty, 0);
      fence_proxy_async();
      named_bar_sync(1, 128);
      if (t2 == 0) {
        const int row0 = tile_of(i) * ROWS;
        if (i < n_valid) {
#pragma unroll
          for (int cb = 0; cb < NKB; ++cb)
#pragma unroll
            for (int h = 0; h < 2; ++h) tma_store_2d(&mout, xb + cb * KBT + h * 8192, cb * 64, row0 + h * 64);
        }
        tma_store_commit();
        tma_store_wait_read0();
        mbar_arrive(&B.x_empty);
      }
    };
    if (n_local > 0) ln(0);
    for (int i = 0; i < n_local; ++i) {
      if (i + 1 < n_local) ln(i + 1);
      epi(i);
    }
    if (t2 == 0) tma_store_wait0();
  }
  tc_fence_before();
  __syncthreads();
  cluster_sync_relaxed();
  if (warp == 2) { tc_fence_after(); tmem_dealloc2(tmem, 512); }
}

// ================================================================================== wiring surface
// Built into a cubin by the newest nvcc that knows sm_100a and launched through the driver API from `transition_sm100.cu`;
// the dynamic shared-memory size the launch must request is exported here so the host never restates it.
extern "C" __device__ int transition_smem_bytes = SMEM_BYTES;
