// tfwd_d384.cu (research source: experiments/transition_fused_sm100/src/tfwd_d384.cu, branch perf/transition-sm100-b200; generated by export_engine.py)
// — the Transition forward at D = 384 (hidden HID = n D; n = 2 by default, 4 with -DHID=1536), bf16, as ONE fused
// sm_100a kernel with 2-CTA tcgen05.mma (the tfwd2.cu / tfwd_d256.cu scheme: the two CTAs of a cluster run their own 128-row tiles in
// lockstep, the leader issues M = 256 products whose B operand is split by N across the pair). What D = 384 changes:
//   * tensor memory: the output accumulator is 384 columns, so there is ONE [a|b] buffer (128 columns, a 64-unit hidden chunk). Both
//     SwiGLU warpgroups take half of every chunk (32 units: a and b in 64 adjacent columns, read by one x64 load) and hand the buffer
//     back as soon as they have read it; h_j goes to shared memory, so expand(j + 1) waits only for that read. (Measured: 32-unit
//     chunks with two [a|b] buffers re-read the 96 KB xn tile for every N = 64 expand, shared-memory bound.)
//   * shared memory: one xn buffer (96 KB; the next tile's x is loaded into it once the current tile's last expand is done and normalised
//     there in place), a 2-stage ring of expand weights (3 K-blocks of [Wa_j 32 | Wb_j 32 units][64 k] per CTA, 24 KB; one wait per
//     12 MMAs: the MMA issue loop shares its SMSP with three busy warps and cannot keep up with a wait per K-block), one stage of this
//     CTA's half of Ws_j ([192 d][64 k] = 24 KB), one h slot ([128][64], 16 KB) and two 16 KB epilogue staging buffers.
//   * the tile boundary is the serial part (the next tile's LayerNorm needs the xn buffer, the next tile's squeeze needs the
//     accumulator drained), so both are spread wide: the LayerNorm runs on 12 warps (three threads per row), and the epilogue of tile i
//     (warps 8-11: residual x by TMA into the staging buffers, x + acc in place, TMA store) overlaps the LayerNorm of tile i + 1.
//   * expand   [a|b]_j = xn [Wa_j; Wb_j]^T   M 256, N 128, K 384 (six 128-B-swizzled K-blocks)
//     squeeze  acc    += h_j Ws_j^T          M 256, N 384 as 256 + 128 (half of each per CTA), K 64, A = h_j from shared memory
// Rounding points as tfwd2.cu: xn bf16, a / b fp32, h = bf16(silu(a) b) (kit sigmoid), acc fp32, out = bf16(x + acc).
// save = 1 (training) also stores xn, the statistics and a, b, h (bf16, [M][H]) for the backward.
// SPDX-License-Identifier: Apache-2.0
#include "sm100.cuh"
using namespace s100;

#ifndef HID
#define HID 768                                                 // hidden units (n x D); n = 2 by default
#endif
constexpr int D_ = 384, H_ = HID, HS = 64, NCH = H_ / HS, ROWS = 128, NKB = D_ / 64;
static_assert(H_ % HS == 0 && NCH >= 2, "whole 64-unit chunks");
constexpr int WSTG = 3, NWK = 2, NWS = 1;                      // expand weight ring: 2 stages of 3 K-blocks; Ws: one stage (needed a
                                                               // chunk period later)
static_assert(NKB == NWK * WSTG, "a chunk's K-blocks fill the weight ring once");
constexpr int NST = 2;                                         // epilogue staging buffers
constexpr int WK = 64 * 128;                                   // one [64 n][64 k] weight K-block, 8 KB
constexpr int WS_SLOT = (128 + 64) * 128;                      // this CTA's rows of the N = 256 and N = 128 parts, [rows][64 k]
constexpr int KBT = ROWS * 128;                                // one K-block of a tile: 16 KB
constexpr int TILE = NKB * KBT;                                // 96 KB
constexpr int O_WAB = 0, O_WS = NWK * WSTG * WK, O_XN = O_WS + NWS * WS_SLOT, O_H = O_XN + TILE, O_ST = O_H + KBT;
constexpr int O_GB = O_ST + NST * KBT;
constexpr int O_EX = O_GB + 2 * D_ * 4;                        // LayerNorm partial sums: [2 passes][3 thirds][128 rows] fp32
constexpr int O_BAR = O_EX + 6 * ROWS * 4;
constexpr int SMEM_BYTES = O_BAR + 512;
static_assert(SMEM_BYTES <= 232448, "shared memory budget");
static_assert(O_WS % 1024 == 0 && O_XN % 1024 == 0 && O_H % 1024 == 0 && O_ST % 1024 == 0 && WS_SLOT % 1024 == 0, "swizzle alignment");
constexpr uint32_t T_OUT = 0, T_AB = D_;                       // OUT 384; AB 128: [a 0..31 | b 0..31 | a 32..63 | b 32..63]
constexpr uint32_t IDESC_EX = idesc_bf16(256, 128), IDESC_SQ0 = idesc_bf16(256, 256), IDESC_SQ1 = idesc_bf16(256, 128);

__device__ __forceinline__ f2 unpack_bf16x2(uint32_t w) { return mk2u(w << 16, w & 0xffff0000u); }
// sigmoid_kit with the first product carrying a zero z read (volatile) after the [a|b] hand-back: a data dependency that keeps ptxas
// from scheduling the SiLU above the arrive (it did, delaying the next expand by the whole SiLU; empty asm pins vanish before ptxas).
// fma(-log2e, a, +0) == fmul(-log2e, a) up to the sign of zero, which ex2 ignores: bit-identical to sigmoid_kit
__device__ __forceinline__ float sigmoid_kit_z(float a, float z) { return rcpf(__fadd_rn(1.f, ex2f(__fmaf_rn(-1.4426950408889634f, a, z)))); }
__device__ __forceinline__ uint32_t ldsv32(uint32_t a) { uint32_t v; asm volatile("ld.volatile.shared.b32 %0, [%1];" : "=r"(v) : "r"(a) : "memory"); return v; }
// one 64-column TMEM load: a and b of a warpgroup's 32 units in one instruction (two x32 loads let ptxas schedule the SiLU of a
// between them, delaying the [a|b] hand-back by the whole SiLU: +17 k clk per 12 chunks, measured)
__device__ __forceinline__ void tmem_ld64(uint32_t taddr, uint32_t (&r)[64]) {
  asm volatile("tcgen05.ld.sync.aligned.32x32b.x64.b32 {%0,%1,%2,%3,%4,%5,%6,%7,%8,%9,%10,%11,%12,%13,%14,%15,%16,%17,%18,%19,%20,%21,%22,%23,%24,%25,%26,%27,%28,%29,%30,%31,%32,%33,%34,%35,%36,%37,%38,%39,%40,%41,%42,%43,%44,%45,%46,%47,%48,%49,%50,%51,%52,%53,%54,%55,%56,%57,%58,%59,%60,%61,%62,%63}, [%64];"
               : "=r"(r[0]), "=r"(r[1]), "=r"(r[2]), "=r"(r[3]), "=r"(r[4]), "=r"(r[5]), "=r"(r[6]), "=r"(r[7]), "=r"(r[8]), "=r"(r[9]), "=r"(r[10]), "=r"(r[11]), "=r"(r[12]), "=r"(r[13]), "=r"(r[14]), "=r"(r[15]), "=r"(r[16]), "=r"(r[17]), "=r"(r[18]), "=r"(r[19]), "=r"(r[20]), "=r"(r[21]), "=r"(r[22]), "=r"(r[23]), "=r"(r[24]), "=r"(r[25]), "=r"(r[26]), "=r"(r[27]), "=r"(r[28]), "=r"(r[29]), "=r"(r[30]), "=r"(r[31]), "=r"(r[32]), "=r"(r[33]), "=r"(r[34]), "=r"(r[35]), "=r"(r[36]), "=r"(r[37]), "=r"(r[38]), "=r"(r[39]), "=r"(r[40]), "=r"(r[41]), "=r"(r[42]), "=r"(r[43]), "=r"(r[44]), "=r"(r[45]), "=r"(r[46]), "=r"(r[47]), "=r"(r[48]), "=r"(r[49]), "=r"(r[50]), "=r"(r[51]), "=r"(r[52]), "=r"(r[53]), "=r"(r[54]), "=r"(r[55]), "=r"(r[56]), "=r"(r[57]), "=r"(r[58]), "=r"(r[59]), "=r"(r[60]), "=r"(r[61]), "=r"(r[62]), "=r"(r[63])
               : "r"(taddr));
}

struct Bars {
  // leader-only: weight fulls (both CTAs' transactions), xn_full (2 LN arrivals), ab_free / h_full (8 warps per CTA), out_empty (4)
  uint64_t wab_full[NWK], ws_full[NWS], xn_full, ab_free, h_full, out_empty;
  // both CTAs (leader's multicast commits)
  uint64_t wab_empty[NWK], ws_empty[NWS], xn_empty, ex_done, sq_done, out_full;
  // local
  uint64_t xl_full, xn_stored, st_full[NST];
  uint32_t tmem, zero;
};

// maps: x, xn, out [M][D] (box 64 x 64); wa, wb [H][D] (box 64 x 32); ws [D][H] (box 64 x 64)
extern "C" __global__ void __launch_bounds__(512, 1)
transition_fwd_d384_sm100(const __grid_constant__ CUtensorMap mx, const __grid_constant__ CUtensorMap mwa,
                          const __grid_constant__ CUtensorMap mwb, const __grid_constant__ CUtensorMap mws,
                          const __grid_constant__ CUtensorMap mxn, const __grid_constant__ CUtensorMap mout,
                          const float* __restrict__ gamma, const float* __restrict__ beta,
                          float* __restrict__ rstd, float* __restrict__ c1, __nv_bfloat16* __restrict__ hs,
                          __nv_bfloat16* __restrict__ as_, __nv_bfloat16* __restrict__ bs, int tiles, float eps, int save) {
  extern __shared__ __align__(1024) uint8_t sm[];
  const uint32_t su = smem_u32(sm);
  Bars& B = *reinterpret_cast<Bars*>(sm + O_BAR);
  const int tid = threadIdx.x, warp = tid >> 5, lane = tid & 31;
  const int cta = blockIdx.x, G = gridDim.x;
  const int crank = (int)cluster_rank();
  const bool leader = crank == 0;
  auto count = [&](int k) { return (tiles > k) ? (tiles - k + G - 1) / G : 0; };
  const int n_valid = count(cta), n_local = count(cta & ~1);
  const int nch = n_local * NCH;
  auto tile_of = [&](int i) { return i < n_valid ? cta + i * G : (n_valid > 0 ? cta + (n_valid - 1) * G : 0); };

  if (tid == 0) {
    for (int s = 0; s < NWK; ++s) { mbar_init(&B.wab_full[s], 1); mbar_init(&B.wab_empty[s], 1); }
    for (int s = 0; s < NWS; ++s) { mbar_init(&B.ws_full[s], 1); mbar_init(&B.ws_empty[s], 1); }
    mbar_init(&B.ab_free, 16); mbar_init(&B.h_full, 16); mbar_init(&B.ex_done, 1); mbar_init(&B.sq_done, 1);
    mbar_init(&B.xn_full, 2); mbar_init(&B.xn_empty, 1); mbar_init(&B.out_empty, 8); mbar_init(&B.out_full, 1);
    mbar_init(&B.xl_full, 1); mbar_init(&B.xn_stored, 1);
    B.zero = 0;
    for (int s = 0; s < NST; ++s) mbar_init(&B.st_full[s], 1);
    fence_barrier_init();
    prefetch_map(&mx); prefetch_map(&mwa); prefetch_map(&mwb); prefetch_map(&mws); prefetch_map(&mxn); prefetch_map(&mout);
  }
  if (tid < D_) { reinterpret_cast<float*>(sm + O_GB)[tid] = gamma[tid]; reinterpret_cast<float*>(sm + O_GB)[D_ + tid] = beta[tid]; }
  if (warp == 2) { tmem_alloc2(smem_u32(&B.tmem), 512); tmem_relinquish2(); }
  tc_fence_before();
  __syncthreads();
  cluster_sync_relaxed();                                      // the barriers were published by fence_barrier_init
  tc_fence_after();
  const uint32_t tmem = B.tmem;

  if (warp < 4) setmaxnreg_dec<56>();
  if (warp == 0) {
    // ------------------------------------------------------------------------------------------ x and Ws producer: x(i) into the xn
    // buffer (for the LayerNorm, once xn(i - 1) is dead), then every chunk's Ws half; Ws transactions complete on the leader's barrier
    if (lane == 0) {
      for (int q = 0; q < nch; ++q) {
        const int i = q / NCH, j = q % NCH;
        if (j == 0) {
          const int row = tile_of(i) * ROWS;
          if (i >= 1) { mbar_wait(&B.xn_empty, (i - 1) & 1); mbar_wait(&B.xn_stored, (i - 1) & 1); }
          mbar_expect_tx(&B.xl_full, TILE);
#pragma unroll
          for (int cb = 0; cb < NKB; ++cb)
#pragma unroll
            for (int h = 0; h < 2; ++h) tma_load_2d(su + O_XN + cb * KBT + h * 8192, &mx, &B.xl_full, cb * 64, row + h * 64);
        }
        const int s = q % NWS;
        if (q >= NWS) mbar_wait(&B.ws_empty[s], ((q / NWS) - 1) & 1);
        if (leader) mbar_expect_tx(&B.ws_full[s], 2 * WS_SLOT);
        const uint32_t slot = su + O_WS + s * WS_SLOT;
        tma_load_2d_2sm(slot, &mws, &B.ws_full[s], j * HS, crank * 128);             // N = 256 part: rows 128 crank .. + 127
        tma_load_2d_2sm(slot + 8192, &mws, &B.ws_full[s], j * HS, crank * 128 + 64);
        tma_load_2d_2sm(slot + 16384, &mws, &B.ws_full[s], j * HS, 256 + crank * 64);  // N = 128 part: rows 256 + 64 crank .. + 63
      }
    }
  } else if (warp == 3) {
    // ------------------------------------------------------------------------------------------ expand weight producer: this CTA's
    // half of every chunk (units 32 crank .. + 31 of Wa and Wb, so that each SwiGLU warpgroup finds its a and b in 64 adjacent TMEM
    // columns), three K-blocks per stage, completing on the leader's barriers
    if (lane == 0) {
      int st = 0;
      for (int c = 0; c < nch; ++c) {
        const int j = c % NCH;
#pragma unroll
        for (int h = 0; h < NWK; ++h, ++st) {
          const int s = st & 1;
          if (st >= NWK) mbar_wait(&B.wab_empty[s], ((st >> 1) - 1) & 1);
          const uint32_t dst = su + O_WAB + s * WSTG * WK;
          if (leader) mbar_expect_tx(&B.wab_full[s], 2 * WSTG * WK);
#pragma unroll
          for (int k = 0; k < WSTG; ++k) {                     // B rows [Wa_j 32 | Wb_j 32] of this CTA's 32 units
            tma_load_2d_2sm(dst + k * WK, &mwa, &B.wab_full[s], (h * WSTG + k) * 64, j * HS + crank * 32);
            tma_load_2d_2sm(dst + k * WK + 4096, &mwb, &B.wab_full[s], (h * WSTG + k) * 64, j * HS + crank * 32);
          }
        }
      }
    }
  } else if (warp == 1 || warp == 2) {
    // ------------------------------------------------------------------------------------------ MMA issue: leader only; warp 1 expands,
    // warp 2 squeezes
    if (leader) {
      if (warp == 1) {
        // one wait per three K-blocks (12 MMAs): with a wait per K-block the issue loop took ~400 clk per K-block (measured) against
        // 256 clk of tensor work
        const uint64_t ad0 = desc_k128(su + O_XN), bd0 = desc_k128(su + O_WAB);
        int st = 0;
        for (int c = 0; c < nch; ++c) {
          const int i = c / NCH, j = c % NCH;
          if (j == 0) mbar_wait_cl(&B.xn_full, i & 1);
          if (c >= 1) mbar_wait_cl(&B.ab_free, (c - 1) & 1);   // the SwiGLU has read [a|b]_{c-1}
#pragma unroll
          for (int h = 0; h < NWK; ++h, ++st) {
            const int s = st & 1;
            mbar_wait(&B.wab_full[s], (st >> 1) & 1);
            tc_fence_after();
            const uint64_t bd = bd0 + (uint64_t)((s * WSTG * WK) >> 4);
            if (elect_one()) {
#pragma unroll
              for (int k = 0; k < WSTG; ++k)
#pragma unroll
                for (int ks = 0; ks < 4; ++ks)
                  umma_ss2(tmem + T_AB, ad0 + (uint64_t)((((h * WSTG + k) * KBT) >> 4) + ks * 2), bd + (uint64_t)(((k * WK) >> 4) + ks * 2),
                           IDESC_EX, (h > 0 || k > 0 || ks > 0) ? 1u : 0u);
              tc_commit2_mc(&B.wab_empty[s], 3);
              if (h == NWK - 1) {
                tc_commit2_mc(&B.ex_done, 3);
                if (j == NCH - 1) tc_commit2_mc(&B.xn_empty, 3);
              }
            }
            __syncwarp();
          }
        }
      } else {
        const uint64_t ha = desc_k128(su + O_H);
        for (int q = 0; q < nch; ++q) {
          const int i = q / NCH, j = q % NCH, sw = q % NWS;
          mbar_wait(&B.ws_full[sw], (q / NWS) & 1);
          mbar_wait_cl(&B.h_full, q & 1);
          if (j == 0 && i >= 1) mbar_wait_cl(&B.out_empty, (i - 1) & 1);
          tc_fence_after();
          const uint64_t b0 = desc_k128(su + O_WS + sw * WS_SLOT), b1 = b0 + (uint64_t)(16384 >> 4);
          if (elect_one()) {
#pragma unroll
            for (int ks = 0; ks < 4; ++ks) {
              const uint32_t acc = (j > 0 || ks > 0) ? 1u : 0u;
              umma_ss2(tmem + T_OUT, ha + (uint64_t)(ks * 2), b0 + (uint64_t)(ks * 2), IDESC_SQ0, acc);
              umma_ss2(tmem + T_OUT + 256, ha + (uint64_t)(ks * 2), b1 + (uint64_t)(ks * 2), IDESC_SQ1, acc);
            }
            tc_commit2_mc(&B.sq_done, 3);
            tc_commit2_mc(&B.ws_empty[sw], 3);
            if (j == NCH - 1) tc_commit2_mc(&B.out_full, 3);
          }
          __syncwarp();
        }
      }
    }
  } else {
    setmaxnreg_inc<152>();
    const uint32_t lb = (uint32_t)(warp & 3) * 32, trow = tmem + (lb << 16);
    const int r = (int)lb + lane;
    // -------------------------------------------------------------------------------------------- LayerNorm of tile i, in place in the
    // xn buffer: warps 4-15, three threads per row (a third of the columns each), fp32x2 arithmetic, partial sums exchanged in smem
    auto ln = [&](int i) {
      constexpr int HK = NKB / 3;
      const int hf = (tid - 128) >> 7;
      float* ex = reinterpret_cast<float*>(sm + O_EX);
      const uint32_t gb = su + O_GB, xb = su + O_XN + hf * HK * KBT;
      const bool real = i < n_valid;
      const int row0 = tile_of(i) * ROWS;
      mbar_wait(&B.xl_full, i & 1);
      f2 s2[2] = {mk2(0.f, 0.f), mk2(0.f, 0.f)};
#pragma unroll
      for (int kb = 0; kb < HK; ++kb)
#pragma unroll
        for (int q = 0; q < 8; ++q) {
          const uint4 t = lds128(xb + kb * KBT + sw128(r, q));
          s2[0] = add2(s2[0], add2(unpack_bf16x2(t.x), unpack_bf16x2(t.y)));
          s2[1] = add2(s2[1], add2(unpack_bf16x2(t.z), unpack_bf16x2(t.w)));
        }
      const f2 st2 = add2(s2[0], s2[1]);
      ex[hf * ROWS + r] = lo2(st2) + hi2(st2);
      named_bar_sync(1, 384);
      const float mean = (ex[r] + ex[ROWS + r] + ex[2 * ROWS + r]) * (1.f / D_);
      const f2 nm2 = mk2(-mean, -mean);
      f2 v2[2] = {mk2(0.f, 0.f), mk2(0.f, 0.f)};
#pragma unroll
      for (int kb = 0; kb < HK; ++kb)
#pragma unroll
        for (int q = 0; q < 8; ++q) {
          const uint4 t = lds128(xb + kb * KBT + sw128(r, q));
          const uint32_t w4[4] = {t.x, t.y, t.z, t.w};
#pragma unroll
          for (int k = 0; k < 4; ++k) {
            const f2 d = add2(unpack_bf16x2(w4[k]), nm2);
            v2[k & 1] = fma2(d, d, v2[k & 1]);
          }
        }
      const f2 vt2 = add2(v2[0], v2[1]);
      ex[(3 + hf) * ROWS + r] = lo2(vt2) + hi2(vt2);
      named_bar_sync(1, 384);
      const float rs = rsqrtf((ex[3 * ROWS + r] + ex[4 * ROWS + r] + ex[5 * ROWS + r]) * (1.f / D_) + eps), cc = mean * rs;
      const f2 rs2 = mk2(rs, rs), ncc2 = mk2(-cc, -cc);
#pragma unroll
      for (int kb = 0; kb < HK; ++kb)
#pragma unroll
        for (int q = 0; q < 8; ++q) {
          const uint32_t ad = xb + kb * KBT + sw128(r, q);
          const uint4 t = lds128(ad);
          const uint32_t w4[4] = {t.x, t.y, t.z, t.w};
          const int col0 = (hf * HK + kb) * 64 + q * 8;
          const uint4 ga = lds128_nv(gb + col0 * 4), gc = lds128_nv(gb + col0 * 4 + 16);
          const uint4 ba = lds128_nv(gb + (D_ + col0) * 4), bc = lds128_nv(gb + (D_ + col0) * 4 + 16);
          const uint32_t g8[8] = {ga.x, ga.y, ga.z, ga.w, gc.x, gc.y, gc.z, gc.w}, b8[8] = {ba.x, ba.y, ba.z, ba.w, bc.x, bc.y, bc.z, bc.w};
          uint32_t o[4];
#pragma unroll
          for (int k = 0; k < 4; ++k) {
            const f2 g2 = mk2u(g8[2 * k], g8[2 * k + 1]), b2 = mk2u(b8[2 * k], b8[2 * k + 1]);
            const f2 y = fma2(unpack_bf16x2(w4[k]), mul2(rs2, g2), fma2(ncc2, g2, b2));   // (x rs - mean rs) g + b
            o[k] = pack_bf16(lo2(y), hi2(y));
          }
          sts128(ad, make_uint4(o[0], o[1], o[2], o[3]));
        }
      if (save && real && hf == 0) { rstd[row0 + r] = rs; c1[row0 + r] = cc; }
      fence_proxy_async();
      named_bar_sync(1, 384);
      if (tid == 256) {
        mbar_arrive_remote_cta(&B.xn_full, 0);
        if (save && real) {
#pragma unroll
          for (int cb = 0; cb < NKB; ++cb)
#pragma unroll
            for (int h = 0; h < 2; ++h) tma_store_2d(&mxn, su + O_XN + cb * KBT + h * 8192, cb * 64, row0 + h * 64);
          tma_store_commit();                                  // read-waited before xn_stored (the loader refills the buffer after it)
        }
      }
    };
    if (warp < 8 || warp >= 12) {
      // ------------------------------------------------------------------------------------------ SwiGLU: both warpgroups on every
      // chunk, warpgroup g taking units 32 g .. 32 g + 31; [a|b] handed back as soon as it is read, h_j into the shared-memory slot
      // (and, in training, a / b / h to global memory). The LayerNorm of each tile comes first.
      const int g = warp >= 12 ? 1 : 0;
      for (int c = 0; c < nch; ++c) {
        const int i = c / NCH, j = c % NCH;
        if (j == 0) ln(i);
        mbar_wait(&B.ex_done, c & 1);
        tc_fence_after();
        uint32_t hp[16], ap[16], bp[16];
        {
          uint32_t ab[64];
          tmem_ld64(trow + T_AB + g * 64, ab);
          tmem_wait_ld();
          const uint32_t* a = ab;
          const uint32_t* b = ab + 32;
          tc_fence_before();
          __syncwarp();
          if (lane == 0) mbar_arrive_remote_relaxed(&B.ab_free, 0);
          const float z = __uint_as_float(ldsv32(smem_u32(&B.zero)));
#pragma unroll
          for (int k = 0; k < 16; ++k) {
            const float a0 = __uint_as_float(a[2 * k]), a1 = __uint_as_float(a[2 * k + 1]);
            const float b0 = __uint_as_float(b[2 * k]), b1 = __uint_as_float(b[2 * k + 1]);
            hp[k] = pack_bf16(a0 * sigmoid_kit_z(a0, z) * b0, a1 * sigmoid_kit_z(a1, z) * b1);
            ap[k] = pack_bf16(a0, a1);
            bp[k] = pack_bf16(b0, b1);
          }
        }
        if (c >= 1) mbar_wait(&B.sq_done, (c - 1) & 1);        // squeeze(c - 1) has read the h slot
#pragma unroll
        for (int q = 0; q < 4; ++q) sts128(su + O_H + sw128(r, g * 4 + q), make_uint4(hp[4 * q], hp[4 * q + 1], hp[4 * q + 2], hp[4 * q + 3]));
        fence_proxy_async();
        __syncwarp();
        if (lane == 0) mbar_arrive_remote_cta(&B.h_full, 0);
        if (save && i < n_valid) {
          // quad transpose (lane k of 4 ends up with 16-byte chunk k of the quad's 4 rows): each store then writes 8 rows x 64 B
          // instead of 32 rows x 16 B (the row-per-thread stores cost ~35 us per 144 tiles in training, measured)
          const int k4 = lane & 3;
          const size_t base = (size_t)(tile_of(i) * ROWS + lb + (lane & ~3)) * H_ + j * HS + g * 32 + k4 * 8;
          auto store_t = [&](__nv_bfloat16* dst, const uint32_t (&v)[16]) {
            uint4 x[4] = {make_uint4(v[0], v[1], v[2], v[3]), make_uint4(v[4], v[5], v[6], v[7]),
                          make_uint4(v[8], v[9], v[10], v[11]), make_uint4(v[12], v[13], v[14], v[15])};
#pragma unroll
            for (int p = 0; p < 2; ++p) {                      // 2x2 blocks: element (k, c) <-> (k ^ 1, c ^ 1) where k, c differ in bit 0
              const bool od = k4 & 1;
              uint4 t = od ? x[2 * p] : x[2 * p + 1];
              t.x = __shfl_xor_sync(0xffffffffu, t.x, 1); t.y = __shfl_xor_sync(0xffffffffu, t.y, 1);
              t.z = __shfl_xor_sync(0xffffffffu, t.z, 1); t.w = __shfl_xor_sync(0xffffffffu, t.w, 1);
              if (od) x[2 * p] = t; else x[2 * p + 1] = t;
            }
#pragma unroll
            for (int p = 0; p < 2; ++p) {                      // blocks: (k, c) <-> (k ^ 2, c ^ 2) where k, c differ in bit 1
              const bool hi = k4 & 2;
              uint4 t = hi ? x[p] : x[p + 2];
              t.x = __shfl_xor_sync(0xffffffffu, t.x, 2); t.y = __shfl_xor_sync(0xffffffffu, t.y, 2);
              t.z = __shfl_xor_sync(0xffffffffu, t.z, 2); t.w = __shfl_xor_sync(0xffffffffu, t.w, 2);
              if (hi) x[p] = t; else x[p + 2] = t;
            }
#pragma unroll
            for (int t = 0; t < 4; ++t) stg128(dst + base + (size_t)t * H_, x[t]);
          };
          store_t(hs, hp);
          store_t(as_, ap);
          store_t(bs, bp);
        }
      }
    } else {
      // ------------------------------------------------------------------------------------------ warps 8-11: LayerNorm of tile i, then
      // the epilogue of tile i - 1 (x + acc through the staging buffers, TMA in and out)
      const int t2 = tid - 256;
      int nu = 0;                                              // staging buffer uses so far (real tiles only): the parity
      auto load_x = [&](int row0, int cb) {
        const int s = cb % NST;
        mbar_expect_tx(&B.st_full[s], KBT);
#pragma unroll
        for (int h = 0; h < 2; ++h) tma_load_2d(su + O_ST + s * KBT + h * 8192, &mx, &B.st_full[s], cb * 64, row0 + h * 64);
      };
      auto epi = [&](int i) {
        const bool real = i < n_valid;
        const int row0 = tile_of(i) * ROWS;
        if (t2 == 0 && real) { load_x(row0, 0); load_x(row0, 1); }
        mbar_wait(&B.out_full, i & 1);
        tc_fence_after();
#pragma unroll 1
        for (int cb = 0; cb < NKB; ++cb) {
          const int s = cb % NST;
          uint32_t acc[2][32];
          tmem_ld32(trow + T_OUT + cb * 64, acc[0]);
          tmem_ld32(trow + T_OUT + cb * 64 + 32, acc[1]);
          tmem_wait_ld();
          if (cb == NKB - 1) {
            tc_fence_before();
            __syncwarp();
            if (lane == 0) mbar_arrive_remote_relaxed(&B.out_empty, 0);
          }
          if (real) {
            mbar_wait(&B.st_full[s], ((nu + cb) / NST) & 1);
            const uint32_t sb = su + O_ST + s * KBT;
#pragma unroll
            for (int q = 0; q < 8; ++q) {
              const uint32_t ad = sb + sw128(r, q);
              const uint4 t = lds128(ad);
              const uint32_t xw[4] = {t.x, t.y, t.z, t.w};
              uint32_t o[4];
#pragma unroll
              for (int k = 0; k < 4; ++k)
                o[k] = pack_bf16(bf16lo(xw[k]) + __uint_as_float(acc[q >> 2][(q & 3) * 8 + 2 * k]),
                                 bf16hi(xw[k]) + __uint_as_float(acc[q >> 2][(q & 3) * 8 + 2 * k + 1]));
              sts128(ad, make_uint4(o[0], o[1], o[2], o[3]));
            }
            fence_proxy_async();
            named_bar_sync(2, 128);
            if (t2 == 0) {
#pragma unroll
              for (int h = 0; h < 2; ++h) tma_store_2d(&mout, sb + h * 8192, cb * 64, row0 + h * 64);
              tma_store_commit();
              if (cb + NST < NKB) { tma_store_wait_read0(); load_x(row0, cb + NST); }   // into the buffer just stored
            }
          }
        }
        if (real) nu += NKB;
      };
      for (int i = 0; i < n_local; ++i) {
        ln(i);
        if (i >= 1) epi(i - 1);
        if (t2 == 0) { tma_store_wait_read0(); mbar_arrive(&B.xn_stored); }
      }
      if (n_local > 0) epi(n_local - 1);
      if (t2 == 0) tma_store_wait0();
    }
  }
  tc_fence_before();
  __syncthreads();
  cluster_sync_relaxed();
  if (warp == 2) { tc_fence_after(); tmem_dealloc2(tmem, 512); }
}

// ================================================================================== wiring surface
// Built into a cubin by the newest nvcc that knows sm_100a and launched through the driver API from `transition_sm100.cu`;
// the dynamic shared-memory size the launch must request is exported here so the host never restates it.
extern "C" __device__ int transition_smem_bytes = SMEM_BYTES;
