// tgate_ab.cu (research source: experiments/transition_fused_sm100/src/tgate_ab.cu, branch perf/transition-sm100-b200; generated by export_engine.py)
// — the wide-width backward gate WITHOUT the fp32 recompute (D = 256 / 384 / 512, H = 4D; -DDIM=<D>): the forward saved a and b
// (bf16); per (128-row tile, 256-unit hidden block)
//   dh = bf16(dy Ws)  (tcgen05, fp32 accumulation)        then from dh and the saved a, b:
//   sig = rcp(1 + ex2(-a log2 e)), silu = a sig,  h = bf16(silu b),  dA = bf16((dh b)(sig + silu(1 - sig))),  dB = bf16(dh silu)
// -> h [M][H], dab [M][2H] (dA | dB). Fuses the dh GEMM with the elementwise gate: dh never leaves the chip.
//
// 2-CTA tcgen05.mma, M = 256 (each CTA its own 128-row tile), N = 256 hidden units split over the pair (leader: Ws^T rows 256 blk ..
// +127, peer: +128 .. +255); dy and B through a 3-stage K-block ring (32 KB per stage and CTA); the accumulator (256 columns) is
// double-buffered in tensor memory. Epilogue: warpgroup g (warps 4-7: g = 0, 12-15: g = 1) takes the block's 64-unit sub-chunks g and
// g + 2: TMA-loads a and b [128][64], computes in two 32-unit passes, writes dA over a and dB over b in place and h into its own staging
// tile, TMA-stores the three. SPDX-License-Identifier: Apache-2.0
#include "sm100.cuh"
using namespace s100;

#ifndef DIM
#define DIM 512
#endif
constexpr int D_ = DIM, H_ = 4 * DIM, NB = 256, NBLK = H_ / NB, ROWS = 128, NKB = D_ / 64;
#ifdef NO_H
constexpr int NST = 3;                                         // no h staging: the forward's h is kept for the backward
constexpr int EPW = 4;                                         // per epilogue warpgroup: 2 x (a/dA | b/dB)
#else
constexpr int NST = 2;                                         // the MMA is a minor part of this kernel
constexpr int EPW = 5;                                         // per epilogue warpgroup: 2 x (a/dA | b/dB) + h
#endif
constexpr int KBT = ROWS * 128;                                // [128][64] bf16 tile, 16 KB
constexpr int S_DY = 0, S_WS = KBT, STAGE = 2 * KBT;           // dy K-block | this CTA's 128 Ws^T rows of the K-block
constexpr int O_ST = 0, O_EP = NST * STAGE;                    // per epilogue warpgroup: 2 x (a/dA | b/dB) + h, 16 KB each
constexpr int O_BAR = O_EP + 2 * EPW * KBT;
constexpr int SMEM_BYTES = O_BAR + 512;
static_assert(SMEM_BYTES <= 232448, "shared memory budget");
constexpr uint32_t IDESC = idesc_bf16(256, NB);

struct Bars {
  uint64_t full[NST];                                          // leader
  uint64_t empty[NST], acc_full[2];                            // both CTAs (multicast commits)
  uint64_t acc_empty[2];                                       // leader: 8 epilogue warps per CTA
  uint64_t ab_full[2][2];                                      // local, per warpgroup and buffer
  uint32_t tmem;
};

// maps: dy [M][D], wst = Ws^T [H][D] (box 64 x 64); a, b [M][H], h [M][H], dab [M][2H] (box 64 x 64)
extern "C" __global__ void __launch_bounds__(512, 1)
transition_gate_ab_sm100(const __grid_constant__ CUtensorMap mdy, const __grid_constant__ CUtensorMap mwst,
                         const __grid_constant__ CUtensorMap ma, const __grid_constant__ CUtensorMap mb,
                         const __grid_constant__ CUtensorMap mh, const __grid_constant__ CUtensorMap mdab, int tiles, int store_h_) {
#ifdef NO_H
  constexpr int store_h = 0; (void)store_h_;
#else
  const int store_h = store_h_;
#endif
  extern __shared__ __align__(1024) uint8_t sm[];
  const uint32_t su = smem_u32(sm);
  Bars& B = *reinterpret_cast<Bars*>(sm + O_BAR);
  const int tid = threadIdx.x, warp = tid >> 5, lane = tid & 31;
  const int cta = blockIdx.x, G = gridDim.x;
  const int crank = (int)cluster_rank();
  const bool leader = crank == 0;
  auto count = [&](int k) { return (tiles > k) ? (tiles - k + G - 1) / G : 0; };
  const int n_valid = count(cta), n_local = count(cta & ~1);
  auto tile_of = [&](int i) { return i < n_valid ? cta + i * G : (n_valid > 0 ? cta + (n_valid - 1) * G : 0); };
#ifdef ITEM_SCHED
  // (tile pair, 256-unit block) items dealt round-robin over all cluster pairs (launch with grid = SM count): small / mid L, where
  // whole tile pairs leave the last wave partly idle (rounds/s1.md)
  const int npairs = G >> 1, pair = cta >> 1, ntot = ((tiles + 1) >> 1) * NBLK;
  const int nitem = (ntot > pair) ? (ntot - pair + npairs - 1) / npairs : 0;
  auto item_blk = [&](int q) { return (pair + q * npairs) % NBLK; };
  auto item_tile = [&](int q) { return 2 * ((pair + q * npairs) / NBLK) + crank; };
  auto item_valid = [&](int q) { return item_tile(q) < tiles; };
  auto item_row = [&](int q) { const int t = item_tile(q); return (t < tiles ? t : tiles - 1) * ROWS; };
#else
  const int nitem = n_local * NBLK;
  auto item_blk = [&](int q) { return q % NBLK; };
  auto item_valid = [&](int q) { return q / NBLK < n_valid; };
  auto item_row = [&](int q) { return tile_of(q / NBLK) * ROWS; };
#endif

  if (tid == 0) {
    for (int s = 0; s < NST; ++s) { mbar_init(&B.full[s], 1); mbar_init(&B.empty[s], 1); }
    for (int s = 0; s < 2; ++s) { mbar_init(&B.acc_full[s], 1); mbar_init(&B.acc_empty[s], 16); mbar_init(&B.ab_full[0][s], 1); mbar_init(&B.ab_full[1][s], 1); }
    fence_barrier_init();
    prefetch_map(&mdy); prefetch_map(&mwst); prefetch_map(&ma); prefetch_map(&mb); prefetch_map(&mh); prefetch_map(&mdab);
  }
  if (warp == 2) { tmem_alloc2(smem_u32(&B.tmem), 512); tmem_relinquish2(); }
  tc_fence_before();
  __syncthreads();
  cluster_sync_relaxed();
  tc_fence_after();
  const uint32_t tmem = B.tmem;

  if (warp < 4) setmaxnreg_dec<56>();
  if (warp == 0) {
    if (lane == 0) {
      int st = 0;
      for (int q = 0; q < nitem; ++q) {
        const int blk = item_blk(q), row = item_row(q);
        for (int kb = 0; kb < NKB; ++kb, ++st) {
          const int s = st % NST;
          if (st >= NST) mbar_wait(&B.empty[s], ((st / NST) - 1) & 1);
          if (leader) mbar_expect_tx(&B.full[s], 2 * STAGE);
          const uint32_t base = su + O_ST + s * STAGE;
#pragma unroll
          for (int h = 0; h < 2; ++h) {
            tma_load_2d_2sm(base + S_DY + h * 8192, &mdy, &B.full[s], kb * 64, row + h * 64);
            tma_load_2d_2sm(base + S_WS + h * 8192, &mwst, &B.full[s], kb * 64, blk * NB + crank * 128 + h * 64);
          }
        }
      }
    }
  } else if (warp == 1) {
    if (leader) {
      int st = 0;
      for (int q = 0; q < nitem; ++q) {
        const int s = q & 1, u = q >> 1;
        if (q >= 2) mbar_wait_cl(&B.acc_empty[s], (u - 1) & 1);
        for (int kb = 0; kb < NKB; ++kb, ++st) {
          const int sg = st % NST;
          mbar_wait(&B.full[sg], (st / NST) & 1);
          tc_fence_after();
          const uint32_t base = su + O_ST + sg * STAGE;
          const uint64_t ddy = desc_k128(base + S_DY), dws = desc_k128(base + S_WS);
          if (elect_one()) {
#pragma unroll
            for (int ks = 0; ks < 4; ++ks)
              umma_ss2(tmem + s * NB, ddy + (uint64_t)(ks * 2), dws + (uint64_t)(ks * 2), IDESC, (kb > 0 || ks > 0) ? 1u : 0u);
            tc_commit2_mc(&B.empty[sg], 3);
            if (kb == NKB - 1) tc_commit2_mc(&B.acc_full[s], 3);
          }
          __syncwarp();
        }
      }
    }
  } else if ((warp >= 4 && warp < 8) || warp >= 12) {
    setmaxnreg_inc<152>();
    const int g = warp >= 12 ? 1 : 0;
    const bool lead = (warp & 3) == 0 && lane == 0;
    const uint32_t lb = (uint32_t)(warp & 3) * 32, r = lb + lane, trow = tmem + (lb << 16);
    const uint32_t ep = su + O_EP + g * EPW * KBT, bh = ep + 4 * KBT;   // buffer x: a/dA at ep + 2x KBT, b/dB at + KBT
    // this warpgroup's sub-chunk sequence: n = 0, 1, ... -> item n / 2, sub-chunk g + 2 (n % 2); buffer n % 2
    const int nsub = nitem * 2;
    auto load_ab = [&](int n) {
      const int q = n >> 1, c = g + 2 * (n & 1), x = n & 1;
      const int row = item_row(q), col = item_blk(q) * NB + c * 64;
      const uint32_t ba = ep + x * 2 * KBT;
      mbar_expect_tx(&B.ab_full[g][x], 2 * KBT);
#pragma unroll
      for (int h = 0; h < 2; ++h) {
        tma_load_2d(ba + h * 8192, &ma, &B.ab_full[g][x], col, row + h * 64);
        tma_load_2d(ba + KBT + h * 8192, &mb, &B.ab_full[g][x], col, row + h * 64);
      }
    };
    if (lead) { if (nsub > 0) load_ab(0); if (nsub > 1) load_ab(1); }
    for (int n = 0; n < nsub; ++n) {
      const int q = n >> 1, cc = n & 1, c = g + 2 * cc, x = n & 1;
      const int s = q & 1, u = q >> 1, blk = item_blk(q);
      const uint32_t ba = ep + x * 2 * KBT, bb = ba + KBT;
      if (cc == 0) { mbar_wait(&B.acc_full[s], u & 1); tc_fence_after(); }
      mbar_wait(&B.ab_full[g][x], (n >> 1) & 1);
      if (n >= 1) {                                             // group n - 1 must have read h (and its buffer, which gets n + 1)
        if (lead) {
          tma_store_wait_read0();
          if (n + 1 < nsub) load_ab(n + 1);
        }
        named_bar_sync(1 + g, 128);
      }
#pragma unroll
      for (int t = 0; t < 2; ++t) {                             // units 32 t .. +31 of the sub-chunk
        uint32_t dh[32];
        tmem_ld32(trow + s * NB + c * 64 + t * 32, dh);
        tmem_wait_ld();
        if (cc == 1 && t == 1) {                                // this warp has read all its columns of the buffer
          tc_fence_before();
          __syncwarp();
          if (lane == 0) mbar_arrive_remote_relaxed(&B.acc_empty[s], 0);
        }
#pragma unroll
        for (int qq = 0; qq < 4; ++qq) {
          const uint32_t off = sw128(r, t * 4 + qq);
          const uint4 av = lds128(ba + off), bv = lds128(bb + off);
          const uint32_t aw[4] = {av.x, av.y, av.z, av.w}, bw[4] = {bv.x, bv.y, bv.z, bv.w};
          uint32_t ho[4], ao[4], bo[4];
#pragma unroll
          for (int e = 0; e < 4; ++e) {
            const int k = qq * 4 + e;
            const uint32_t gp = pack_bf16(__uint_as_float(dh[2 * k]), __uint_as_float(dh[2 * k + 1]));
            const float g0 = bf16lo(gp), g1 = bf16hi(gp);
            const float a0 = bf16lo(aw[e]), a1 = bf16hi(aw[e]), b0 = bf16lo(bw[e]), b1 = bf16hi(bw[e]);
            const float s0 = sigmoid_kit(a0), s1 = sigmoid_kit(a1), l0 = a0 * s0, l1 = a1 * s1;
            ho[e] = pack_bf16(l0 * b0, l1 * b1);
            ao[e] = pack_bf16((g0 * b0) * (s0 + l0 * (1.f - s0)), (g1 * b1) * (s1 + l1 * (1.f - s1)));
            bo[e] = pack_bf16(g0 * l0, g1 * l1);
          }
          if (store_h) sts128(bh + off, make_uint4(ho[0], ho[1], ho[2], ho[3]));
          sts128(ba + off, make_uint4(ao[0], ao[1], ao[2], ao[3]));
          sts128(bb + off, make_uint4(bo[0], bo[1], bo[2], bo[3]));
        }
      }
      fence_proxy_async();
      named_bar_sync(1 + g, 128);
      if (lead) {
        if (item_valid(q)) {
          const int row = item_row(q), col = blk * NB + c * 64;
#pragma unroll
          for (int h = 0; h < 2; ++h) {
            if (store_h) tma_store_2d(&mh, bh + h * 8192, col, row + h * 64);
            tma_store_2d(&mdab, ba + h * 8192, col, row + h * 64);
            tma_store_2d(&mdab, bb + h * 8192, H_ + col, row + h * 64);
          }
        }
        tma_store_commit();
      }
    }
    if (lead) tma_store_wait0();
  }
  tc_fence_before();
  __syncthreads();
  cluster_sync_relaxed();
  if (warp == 2) { tc_fence_after(); tmem_dealloc2(tmem, 512); }
}

// ================================================================================== wiring surface
// Built into a cubin by the newest nvcc that knows sm_100a and launched through the driver API from `transition_sm100.cu`;
// the dynamic shared-memory size the launch must request is exported here so the host never restates it.
extern "C" __device__ int transition_smem_bytes = SMEM_BYTES;
