// tgate_w.cu (research source: experiments/transition_fused_sm100/src/tgate_w.cu, branch perf/transition-sm100-b200; generated by export_engine.py)
// — the Transition backward's GATE stage for the wide widths (D = 256 / 384 / 512, H = 4D; -DDIM=<D>), sm_100a, bf16:
// per (128-row tile, 64-unit hidden chunk j)
//   dh_j  = bf16(dy Ws[:, j])      [a|b]_j = xn [Wa_j; Wb_j]^T (fp32)      sig = rcp(1 + ex2(-a log2 e)), silu = a sig
//   h_j   = bf16(silu b)    dA_j = bf16((dh b)(sig + silu(1 - sig)))    dB_j = bf16(dh silu)       (the tbwd.cu contract)
// written to h [M][H] (optional) and dab [M][2H] (dA | dB). The weight gradients (cuBLAS) and d_xn + LayerNorm backward follow.
//
// 2-CTA tcgen05.mma: the two CTAs of a cluster run their own 128-row tiles in lockstep over the same chunk sequence; the leader issues
// M = 256 products whose B operand is split by N across the pair (dh: Ws_j^T rows hs 32 crank .. +31; [a|b]: the leader holds Wa_j,
// the peer Wb_j). A (dy, xn) and B stream through a 4-stage ring in 64-column K-blocks (44 KB per stage and CTA). The accumulators
// ([a|b] 128 + dh 64 columns) are double-buffered in tensor memory so the gate of item q overlaps the products of item q + 1; the gate
// runs on two warpgroups (hidden units 0..31 / 32..63) and stages h, dA, dB in shared memory for TMA stores.
// SPDX-License-Identifier: Apache-2.0
#include "sm100.cuh"
using namespace s100;

#ifndef DIM
#define DIM 256
#endif
#ifndef HID
#define HID (4 * DIM)                                                // hidden units (n x D); n = 4 by default
#endif
constexpr int D_ = DIM, H_ = HID, HS = 64, NCH = H_ / HS, ROWS = 128, NKB = D_ / 64;
#ifndef NST_
#define NST_ 4
#endif
#ifndef NSTG
#define NSTG 1                                                 // staging buffers (h | dA | dB), 48 KB each
#endif
constexpr int NST = NST_;                                      // ring stages
constexpr int KBT = ROWS * 128;                                // one K-block of a 128-row tile: 16 KB
constexpr int S_DY = 0, S_XN = KBT, S_WAB = 2 * KBT, S_WS = 2 * KBT + 8192, STAGE = 2 * KBT + 8192 + 4096;   // 44 KB
constexpr int O_ST = 0, O_OUT = NST * STAGE;                   // staging: h | dA | dB, [128][64] each
constexpr int O_BAR = O_OUT + NSTG * 3 * KBT;
constexpr int SMEM_BYTES = O_BAR + 512;
static_assert(SMEM_BYTES <= 232448, "shared memory budget");
static_assert(STAGE % 1024 == 0 && O_OUT % 1024 == 0, "1 KB alignment of swizzled tiles");
constexpr uint32_t IDESC_DH = idesc_bf16(256, 64), IDESC_AB = idesc_bf16(256, 128);
constexpr uint32_t T_AB = 0, T_DH = 256;                       // accumulator buffer s: [a|b] at 128 s, dh at 256 + 64 s

struct Bars {
  uint64_t full[NST];                                          // leader: both CTAs' stage transactions
  uint64_t empty[NST], acc_full[2];                            // both CTAs (leader's multicast commits)
  uint64_t acc_empty[2];                                       // leader: 4 gate warps per CTA read the buffer
  uint64_t staged[NSTG], stage_free[NSTG];                     // local: gate warps -> store thread -> gate warps
  uint32_t tmem;
};

DEVI void gate_pair16(uint32_t dh0, uint32_t dh1, uint32_t a0, uint32_t a1, uint32_t b0, uint32_t b1, uint32_t& hp, uint32_t& dap, uint32_t& dbp) {
  const uint32_t gp = pack_bf16(__uint_as_float(dh0), __uint_as_float(dh1));
  const f2 G = mk2(bf16lo(gp), bf16hi(gp)), A = mk2u(a0, a1), Bv = mk2u(b0, b1);
  const f2 S = mk2(sigmoid_kit(__uint_as_float(a0)), sigmoid_kit(__uint_as_float(a1)));
  const f2 L = mul2(A, S);
  const f2 H = mul2(L, Bv), DB = mul2(G, L);
  const f2 U = fma2(L, fma2(S, mk2(-1.f, -1.f), mk2(1.f, 1.f)), S);
  const f2 DA = mul2(mul2(G, Bv), U);
  hp = pack_bf16(lo2(H), hi2(H)); dap = pack_bf16(lo2(DA), hi2(DA)); dbp = pack_bf16(lo2(DB), hi2(DB));
}

// maps: dy, xn [M][D] (box 64 x 64); wst = Ws^T [H][D] (box 64 x 32); wa, wb [H][D] (box 64 x 64); h [M][H], dab [M][2H] (box 64 x 64)
extern "C" __global__ void __launch_bounds__(512, 1)
transition_gate_w_sm100(const __grid_constant__ CUtensorMap mdy, const __grid_constant__ CUtensorMap mxn,
                        const __grid_constant__ CUtensorMap mwst, const __grid_constant__ CUtensorMap mwa,
                        const __grid_constant__ CUtensorMap mwb, const __grid_constant__ CUtensorMap mh,
                        const __grid_constant__ CUtensorMap mdab, int tiles, int store_h) {
  extern __shared__ __align__(1024) uint8_t sm[];
  const uint32_t su = smem_u32(sm);
  Bars& B = *reinterpret_cast<Bars*>(sm + O_BAR);
  const int tid = threadIdx.x, warp = tid >> 5, lane = tid & 31;
  const int cta = blockIdx.x, G = gridDim.x;
  const int crank = (int)cluster_rank();
  const bool leader = crank == 0;
  auto count = [&](int k) { return (tiles > k) ? (tiles - k + G - 1) / G : 0; };
  const int n_valid = count(cta), n_local = count(cta & ~1);   // the pair walks the leader's count; a short CTA repeats its last
  const int nitem = n_local * NCH;                              // tile as a dummy whose results are not stored
  auto tile_of = [&](int i) { return i < n_valid ? cta + i * G : (n_valid > 0 ? cta + (n_valid - 1) * G : 0); };

  if (tid == 0) {
    for (int s = 0; s < NST; ++s) { mbar_init(&B.full[s], 1); mbar_init(&B.empty[s], 1); }
    for (int s = 0; s < 2; ++s) { mbar_init(&B.acc_full[s], 1); mbar_init(&B.acc_empty[s], 16); }   // 8 warps (both warpgroups) in each CTA of the pair
    for (int s = 0; s < NSTG; ++s) { mbar_init(&B.staged[s], 8); mbar_init(&B.stage_free[s], 1); }
    fence_barrier_init();
    prefetch_map(&mdy); prefetch_map(&mxn); prefetch_map(&mwst); prefetch_map(&mwa); prefetch_map(&mwb); prefetch_map(&mh); prefetch_map(&mdab);
  }
  if (warp == 2) { tmem_alloc2(smem_u32(&B.tmem), 512); tmem_relinquish2(); }
  tc_fence_before();
  __syncthreads();
  cluster_sync_relaxed();
  tc_fence_after();
  const uint32_t tmem = B.tmem;

  if (warp < 4) setmaxnreg_dec<56>();
  if (warp == 0) {
    // ------------------------------------------------------------------------------------------ producer: per (item, K-block) this CTA's
    // dy / xn K-block (own rows) and its half of the B operands; completions counted on the leader's barrier
    if (lane == 0) {
      const CUtensorMap* mab = leader ? &mwa : &mwb;
      int st = 0;
      for (int q = 0; q < nitem; ++q) {
        const int i = q / NCH, j = q % NCH, row = tile_of(i) * ROWS;
        for (int kb = 0; kb < NKB; ++kb, ++st) {
          const int s = st % NST;
          if (st >= NST) mbar_wait(&B.empty[s], ((st / NST) - 1) & 1);
          if (leader) mbar_expect_tx(&B.full[s], 2 * STAGE);
          const uint32_t base = su + O_ST + s * STAGE;
#pragma unroll
          for (int h = 0; h < 2; ++h) {
            tma_load_2d_2sm(base + S_DY + h * 8192, &mdy, &B.full[s], kb * 64, row + h * 64);
            tma_load_2d_2sm(base + S_XN + h * 8192, &mxn, &B.full[s], kb * 64, row + h * 64);
          }
          tma_load_2d_2sm(base + S_WAB, mab, &B.full[s], kb * 64, j * HS);
          tma_load_2d_2sm(base + S_WS, &mwst, &B.full[s], kb * 64, j * HS + crank * 32);
        }
      }
    }
  } else if (warp == 1) {
    // ------------------------------------------------------------------------------------------ MMA (leader)
    if (leader) {
      int st = 0;
      for (int q = 0; q < nitem; ++q) {
        const int s = q & 1, u = q >> 1;
        if (q >= 2) mbar_wait_cl(&B.acc_empty[s], (u - 1) & 1);
        for (int kb = 0; kb < NKB; ++kb, ++st) {
          const int sg = st % NST;
          mbar_wait(&B.full[sg], (st / NST) & 1);
          tc_fence_after();
          const uint32_t base = su + O_ST + sg * STAGE;
          const uint64_t ddy = desc_k128(base + S_DY), dxn = desc_k128(base + S_XN);
          const uint64_t dab = desc_k128(base + S_WAB), dws = desc_k128(base + S_WS);
          if (elect_one()) {
#pragma unroll
            for (int ks = 0; ks < 4; ++ks) {
              umma_ss2(tmem + T_DH + s * 64, ddy + (uint64_t)(ks * 2), dws + (uint64_t)(ks * 2), IDESC_DH, (kb > 0 || ks > 0) ? 1u : 0u);
              umma_ss2(tmem + T_AB + s * 128, dxn + (uint64_t)(ks * 2), dab + (uint64_t)(ks * 2), IDESC_AB, (kb > 0 || ks > 0) ? 1u : 0u);
            }
            tc_commit2_mc(&B.empty[sg], 3);
            if (kb == NKB - 1) tc_commit2_mc(&B.acc_full[s], 3);
          }
          __syncwarp();
        }
      }
    }
  } else if ((warp >= 4 && warp < 8) || warp >= 12) {
    // ------------------------------------------------------------------------------------------ gate: warps 4-7 units 0..31, 12-15 32..63
    setmaxnreg_inc<152>();
    const uint32_t lb = (uint32_t)(warp & 3) * 32, r = lb + lane, trow = tmem + (lb << 16);
    const int half = warp >= 12 ? 1 : 0;
    for (int q = 0; q < nitem; ++q) {
      const int s = q & 1, u = q >> 1;
      mbar_wait(&B.acc_full[s], u & 1);
      tc_fence_after();
      uint32_t dh[32], av[32], bv[32];
      tmem_ld32(trow + T_DH + s * 64 + half * 32, dh);
      tmem_ld32(trow + T_AB + s * 128 + half * 32, av);
      tmem_ld32(trow + T_AB + s * 128 + 64 + half * 32, bv);
      tmem_wait_ld();
      tc_fence_before();
      __syncwarp();
      if (lane == 0) mbar_arrive_remote_relaxed(&B.acc_empty[s], 0);
      const int sb = q % NSTG;
      const uint32_t ob = su + O_OUT + sb * 3 * KBT;
      if (q >= NSTG) mbar_wait(&B.stage_free[sb], ((q / NSTG) - 1) & 1);
#pragma unroll
      for (int qq = 0; qq < 4; ++qq) {                       // 8 hidden units -> one 16-byte chunk of h, dA and dB each
        uint32_t hp[4], dap[4], dbp[4];
#pragma unroll
        for (int kk = 0; kk < 4; ++kk) {
          const int k = qq * 4 + kk;
          gate_pair16(dh[2 * k], dh[2 * k + 1], av[2 * k], av[2 * k + 1], bv[2 * k], bv[2 * k + 1], hp[kk], dap[kk], dbp[kk]);
        }
        const uint32_t off = sw128(r, half * 4 + qq);
        sts128(ob + off, make_uint4(hp[0], hp[1], hp[2], hp[3]));
        sts128(ob + KBT + off, make_uint4(dap[0], dap[1], dap[2], dap[3]));
        sts128(ob + 2 * KBT + off, make_uint4(dbp[0], dbp[1], dbp[2], dbp[3]));
      }
      fence_proxy_async();
      __syncwarp();
      if (lane == 0) mbar_arrive(&B.staged[sb]);
    }
  } else if (warp == 8) {
    // ------------------------------------------------------------------------------------------ stores
    if (lane == 0) {
      for (int q = 0; q < nitem; ++q) {
        const int i = q / NCH, j = q % NCH;
        const int sb = q % NSTG;
        mbar_wait(&B.staged[sb], (q / NSTG) & 1);
        const uint32_t ob = su + O_OUT + sb * 3 * KBT;
        if (i < n_valid) {
          const int row = tile_of(i) * ROWS;
#pragma unroll
          for (int h = 0; h < 2; ++h) {
            if (store_h) tma_store_2d(&mh, ob + h * 8192, j * HS, row + h * 64);
            tma_store_2d(&mdab, ob + KBT + h * 8192, j * HS, row + h * 64);
            tma_store_2d(&mdab, ob + 2 * KBT + h * 8192, H_ + j * HS, row + h * 64);
          }
        }
        tma_store_commit();
        // release the buffer used NSTG items ago once its store has read it (keep NSTG - 1 stores in flight)
        if (NSTG == 1) { tma_store_wait_read0(); mbar_arrive(&B.stage_free[sb]); }
        else {
          asm volatile("cp.async.bulk.wait_group.read 1;" ::: "memory");
          if (q >= 1) mbar_arrive(&B.stage_free[(q - 1) % NSTG]);
        }
      }
      tma_store_wait0();
    }
  }
  tc_fence_before();
  __syncthreads();
  cluster_sync_relaxed();
  if (warp == 2) { tc_fence_after(); tmem_dealloc2(tmem, 512); }
}

// ================================================================================== wiring surface
// Built into a cubin by the newest nvcc that knows sm_100a and launched through the driver API from `transition_sm100.cu`;
// the dynamic shared-memory size the launch must request is exported here so the host never restates it.
extern "C" __device__ int transition_smem_bytes = SMEM_BYTES;
