// tln_w.cu (research source: experiments/transition_fused_sm100/src/tln_w.cu, branch perf/transition-sm100-b200; generated by export_engine.py)
// — the input LayerNorm of the two-kernel Transition forward (D = 384 / 512; -DDIM=<D>): one warp per row, 8 columns (16 B)
// per lane access, two passes over registers; writes xn (bf16, the expand's A operand and the backward's save) and the statistics
// rstd, c1 = mean rstd. Same rounding point as the fused kernels: xn = bf16((x - mean) rstd gamma + beta).
// SPDX-License-Identifier: Apache-2.0
#include <cuda_bf16.h>
#include <stdint.h>

#ifndef DIM
#define DIM 384
#endif
#ifndef LPR
#define LPR 16                                                 // lanes per row: 16 (two rows per warp) or 32
#endif
constexpr int D_ = DIM, NCHK = D_ / 8, PER = NCHK / LPR, RPW = 32 / LPR;
static_assert(NCHK % LPR == 0, "whole chunks per lane");

__device__ __forceinline__ float lo(uint32_t v) { return __uint_as_float(v << 16); }
__device__ __forceinline__ float hi(uint32_t v) { return __uint_as_float(v & 0xffff0000u); }
__device__ __forceinline__ uint32_t pk(float a, float b) { uint32_t r; asm("cvt.rn.bf16x2.f32 %0, %1, %2;" : "=r"(r) : "f"(b), "f"(a)); return r; }

extern "C" __global__ void __launch_bounds__(256)
transition_ln_w(const __nv_bfloat16* __restrict__ x, const float* __restrict__ gamma, const float* __restrict__ beta,
                __nv_bfloat16* __restrict__ xn, float* __restrict__ rstd, float* __restrict__ c1, int M, float eps, int save_stats) {
  const int lane = threadIdx.x % LPR;
  const int rpb = (blockDim.x >> 5) * RPW;
  for (int row = blockIdx.x * rpb + (threadIdx.x >> 5) * RPW + (threadIdx.x & 31) / LPR; row < M; row += gridDim.x * rpb) {
    const uint4* xr = reinterpret_cast<const uint4*>(x + (size_t)row * D_);
    uint4 v[PER];
    float s = 0.f;
#pragma unroll
    for (int k = 0; k < PER; ++k) {
      const int c = lane + LPR * k;
      {
        v[k] = __ldcs(xr + c);
        s += ((lo(v[k].x) + hi(v[k].x)) + (lo(v[k].y) + hi(v[k].y))) + ((lo(v[k].z) + hi(v[k].z)) + (lo(v[k].w) + hi(v[k].w)));
      }
    }
#pragma unroll
    for (int o = LPR / 2; o; o >>= 1) s += __shfl_xor_sync(0xffffffffu, s, o);
    const float mean = s * (1.f / D_);
    float q = 0.f;
#pragma unroll
    for (int k = 0; k < PER; ++k) {
      const int c = lane + LPR * k;
      {
        const uint32_t w[4] = {v[k].x, v[k].y, v[k].z, v[k].w};
#pragma unroll
        for (int e = 0; e < 4; ++e) { const float d0 = lo(w[e]) - mean, d1 = hi(w[e]) - mean; q += d0 * d0 + d1 * d1; }
      }
    }
#pragma unroll
    for (int o = LPR / 2; o; o >>= 1) q += __shfl_xor_sync(0xffffffffu, q, o);
    const float rs = rsqrtf(q * (1.f / D_) + eps);
    uint4* xo = reinterpret_cast<uint4*>(xn + (size_t)row * D_);
#pragma unroll
    for (int k = 0; k < PER; ++k) {
      const int c = lane + LPR * k;
      {
        const uint32_t w[4] = {v[k].x, v[k].y, v[k].z, v[k].w};
        uint32_t o[4];
        const float4 g0 = __ldg(reinterpret_cast<const float4*>(gamma) + 2 * c), g1 = __ldg(reinterpret_cast<const float4*>(gamma) + 2 * c + 1);
        const float4 b0 = __ldg(reinterpret_cast<const float4*>(beta) + 2 * c), b1 = __ldg(reinterpret_cast<const float4*>(beta) + 2 * c + 1);
        const float g[8] = {g0.x, g0.y, g0.z, g0.w, g1.x, g1.y, g1.z, g1.w}, b[8] = {b0.x, b0.y, b0.z, b0.w, b1.x, b1.y, b1.z, b1.w};
#pragma unroll
        for (int e = 0; e < 4; ++e)
          o[e] = pk((lo(w[e]) - mean) * rs * g[2 * e] + b[2 * e], (hi(w[e]) - mean) * rs * g[2 * e + 1] + b[2 * e + 1]);
        xo[c] = make_uint4(o[0], o[1], o[2], o[3]);
      }
    }
    if (save_stats && lane == 0) { rstd[row] = rs; c1[row] = mean * rs; }
  }
}
