// tsmall_w.cu (research source: experiments/transition_fused_sm100/src/tsmall_w.cu, branch perf/transition-sm100-b200; generated by export_engine.py)
// — the Transition forward for SMALL M (a few 128-row tiles, e.g. a single-stream [B, L, D] activation), D <= 384,
// hidden H = HID (-DDIM=<D> -DHID=<H> -DCL=<cluster size>), sm_100a, bf16: ONE kernel, LayerNorm + expand + SwiGLU + squeeze +
// residual, with the hidden dimension split over a CLUSTER. The per-tile kernels keep one SM (pair) per tile busy for the whole
// hidden loop; at 3-6 tiles that is 3-6 % of the card. Here a cluster of CL CTAs owns one 128-row tile:
//   * every CTA TMA-loads the tile's x and normalises it (statistics recomputed per CTA: 128 x D, cheap; fp32x2 arithmetic)
//   * CTA c runs the hidden slice [c S, (c + 1) S), S = H / CL, in 64-unit chunks: expand [a|b]_j = xn [Wa_j; Wb_j]^T (M 128, N 128,
//     K D) into tensor memory, SwiGLU on a warpgroup (h_j = bf16(silu(a) b) into shared memory), squeeze acc += h_j Ws_j^T (N = D,
//     two MMAs when D > 256) into a [128 x D] fp32 accumulator in tensor memory (D + 128 <= 512 columns)
//   * the partial accumulators are summed ACROSS the cluster: CTA o owns output columns [o W, (o + 1) W), W = D / CL. Every CTA
//     drains the other owners' blocks from tensor memory in 32-column boxes and TMA-stores each box to an fp32 scratch
//     [tile][CTA][128][D] as soon as it is drained; after a cluster barrier the owner TMA-loads its block of the other CTAs' partials,
//     adds them to its own block (straight from tensor memory) in a fixed order, adds the residual and writes bf16(acc + x):
//     deterministic, one rounding. (Measured alternatives: thread-level distributed-shared-memory stores / loads 12-17 us, a
//     pipelined distributed-shared-memory DMA ring ~8.5 us for the same 192 KB per CTA.)
// The fp32 summation order (per-CTA slices, then across the cluster) differs from the per-tile kernels' (chunk after chunk), so
// the two builds agree to fp32 rounding, not bit for bit; each is bit-reproducible run to run.
// -DSAVE_AB: training -- rank 0 also stores xn and the statistics, and every CTA stores its slice of h, a, b (bf16).
// SPDX-License-Identifier: Apache-2.0
#include "sm100.cuh"
using namespace s100;

#ifndef DIM
#define DIM 384
#endif
#ifndef HID
#define HID (2 * DIM)
#endif
#ifndef CL
#define CL 12
#endif
constexpr int D_ = DIM, H_ = HID, ROWS = 128, NKB = D_ / 64, S_ = H_ / CL, NCH = S_ / 64, W_ = D_ / CL, NBX = W_ / 32;
static_assert(D_ % 192 == 0 && D_ + 128 <= 512, "the [128 x D] accumulator and one [a|b] chunk share the 512 TMEM columns");
static_assert(H_ % (64 * CL) == 0 && W_ % 32 == 0, "whole 64-unit chunks per CTA, whole 32-column fp32 boxes per owner");
// CL = 1: one CTA per tile, no reduction (the epilogue adds the residual straight from tensor memory)
constexpr int KBT = ROWS * 128;                                // one [128 rows][64] bf16 K-block, 16 KB; also one [128][32] fp32 box
constexpr int NWR = 3;                                         // expand weight ring (K-blocks of [Wa_j; Wb_j])
constexpr int O_XN = 0, O_WAB = NKB * KBT, O_WS = O_WAB + NWR * KBT, O_H = O_WS + D_ * 128, O_END = O_H + KBT;
constexpr int O_RED = 0;                                       // after the MMAs: D / 32 drain boxes, then CL * NBX owner boxes
static_assert((D_ / 32) * KBT <= O_END && CL * NBX * KBT <= O_END, "the reduction boxes fit the dead buffers");
constexpr int O_GB = (O_END + 1023) & ~1023;
constexpr int O_EX = O_GB + 2 * D_ * 4;                        // LayerNorm row sums: [2 passes][3 thirds][128 rows] fp32
constexpr int O_BAR = O_EX + 6 * ROWS * 4;
constexpr int SMEM_BYTES = O_BAR + 512;
static_assert(SMEM_BYTES <= 232448, "shared memory budget");
constexpr uint32_t T_ACC = 0, T_AB = D_;                       // accumulator columns 0 .. D-1, [a|b] D .. D+127
constexpr uint32_t IDESC_EX = idesc_bf16(128, 128);

struct Bars {
  uint64_t x_full, xn_full, xn_stored, ws_full, ws_empty, ex_done, ab_free, h_full, h_empty, acc_full, red_full;
  uint64_t wab_full[NWR], wab_empty[NWR];
  uint32_t tmem;
};

DEVI uint32_t box_off(int box, int r, int q) { return (uint32_t)(box * KBT + r * 128 + ((q ^ (r & 7)) << 4)); }   // [128][32] fp32, SW128
DEVI f2 unpack_bf16x2(uint32_t w) { return mk2u(w << 16, w & 0xffff0000u); }

// maps: x, xn [M][D] (box 64 x 128); wa, wb [H][D] (box 64 x 64); ws [D][H] (box 64 x 64); part [tiles CL 128][D] fp32 (box 32 x 128)
extern "C" __global__ void __launch_bounds__(512, 1)
transition_small_w_sm100(const __grid_constant__ CUtensorMap mx, const __grid_constant__ CUtensorMap mwa,
                         const __grid_constant__ CUtensorMap mwb, const __grid_constant__ CUtensorMap mws,
                         const __grid_constant__ CUtensorMap mxn, const __grid_constant__ CUtensorMap mpart,
                         const __nv_bfloat16* __restrict__ xg, __nv_bfloat16* __restrict__ out, const float* __restrict__ gamma,
                         const float* __restrict__ beta, float* __restrict__ rstd, float* __restrict__ c1,
                         __nv_bfloat16* __restrict__ hs, __nv_bfloat16* __restrict__ as_, __nv_bfloat16* __restrict__ bs, float eps,
                         int save) {
  extern __shared__ __align__(1024) uint8_t sm[];
  const uint32_t su = smem_u32(sm);
  Bars& B = *reinterpret_cast<Bars*>(sm + O_BAR);
  const int tid = threadIdx.x, warp = tid >> 5, lane = tid & 31;
  const int rank = (int)cluster_rank(), tile = blockIdx.x / CL, row0 = tile * ROWS, hs0 = rank * S_;
  const bool saver = save && rank == 0;

  if (tid == 0) {
    mbar_init(&B.x_full, 1); mbar_init(&B.xn_full, 1); mbar_init(&B.xn_stored, 1); mbar_init(&B.ws_full, 1);
    mbar_init(&B.ws_empty, 1); mbar_init(&B.ex_done, 1); mbar_init(&B.ab_free, 4); mbar_init(&B.h_full, 4);
    mbar_init(&B.h_empty, 1); mbar_init(&B.acc_full, 1); mbar_init(&B.red_full, 1);
    for (int s = 0; s < NWR; ++s) { mbar_init(&B.wab_full[s], 1); mbar_init(&B.wab_empty[s], 1); }
    fence_barrier_init();
    fence_proxy_async();
    mbar_expect_tx(&B.x_full, NKB * KBT);
    for (int kb = 0; kb < NKB; ++kb) tma_load_2d(su + O_XN + kb * KBT, &mx, &B.x_full, kb * 64, row0);
    prefetch_map(&mwa); prefetch_map(&mwb); prefetch_map(&mws); prefetch_map(&mxn); prefetch_map(&mpart);
  }
  if (warp == 2) { tmem_alloc(smem_u32(&B.tmem), 512); tmem_relinquish(); }
  if (warp >= 4 && warp < 8)                                   // gamma / beta, by the LayerNorm warps
    for (int c = tid - 128; c < D_; c += 128) {
      reinterpret_cast<float*>(sm + O_GB)[c] = gamma[c]; reinterpret_cast<float*>(sm + O_GB)[D_ + c] = beta[c];
    }
  tc_fence_before();
  __syncthreads();
  tc_fence_after();
  const uint32_t tmem = B.tmem;

  if (warp == 0) {
    // ------------------------------------------------------------------------------------------ weight producer
    if (lane == 0) {
      int st = 0;
      for (int j = 0; j < NCH; ++j) {
        const int h0 = hs0 + j * 64;
        for (int kb = 0; kb < NKB; ++kb, ++st) {
          const int s = st % NWR;
          if (st >= NWR) mbar_wait(&B.wab_empty[s], ((st / NWR) - 1) & 1);
          mbar_expect_tx(&B.wab_full[s], KBT);
          tma_load_2d(su + O_WAB + s * KBT, &mwa, &B.wab_full[s], kb * 64, h0);
          tma_load_2d(su + O_WAB + s * KBT + 8192, &mwb, &B.wab_full[s], kb * 64, h0);
        }
        if (j >= 1) mbar_wait(&B.ws_empty, (j - 1) & 1);
        mbar_expect_tx(&B.ws_full, D_ * 128);
        for (int db = 0; db < D_ / 64; ++db) tma_load_2d(su + O_WS + db * 8192, &mws, &B.ws_full, h0, db * 64);
      }
    }
  } else if (warp == 1) {
    // ------------------------------------------------------------------------------------------ MMA issue (converged warp)
    mbar_wait(&B.xn_full, 0);
    int st = 0;
    for (int j = 0; j < NCH; ++j) {
      if (j >= 1) mbar_wait(&B.ab_free, (j - 1) & 1);          // SwiGLU(j - 1) has read [a|b]
      tc_fence_after();
      for (int kb = 0; kb < NKB; ++kb, ++st) {
        const int s = st % NWR;
        mbar_wait(&B.wab_full[s], (st / NWR) & 1);
        tc_fence_after();
        const uint64_t da = desc_k128(su + O_XN + kb * KBT), db = desc_k128(su + O_WAB + s * KBT);
        if (elect_one()) {
#pragma unroll
          for (int ks = 0; ks < 4; ++ks)
            umma_ss(tmem + T_AB, da + (uint64_t)(ks * 2), db + (uint64_t)(ks * 2), IDESC_EX, (kb > 0 || ks > 0) ? 1u : 0u);
          tc_commit(&B.wab_empty[s]);
          if (kb == NKB - 1) tc_commit(&B.ex_done);
        }
        __syncwarp();
      }
      mbar_wait(&B.h_full, j & 1);
      mbar_wait(&B.ws_full, j & 1);
      tc_fence_after();
      const uint64_t dh = desc_k128(su + O_H), dw = desc_k128(su + O_WS);
      if (elect_one()) {
#pragma unroll
        for (int ks = 0; ks < 4; ++ks) {
          const uint32_t acc = (j > 0 || ks > 0) ? 1u : 0u;
          if (D_ <= 256) {
            umma_ss(tmem + T_ACC, dh + (uint64_t)(ks * 2), dw + (uint64_t)(ks * 2), idesc_bf16(128, D_), acc);
          } else {
            umma_ss(tmem + T_ACC, dh + (uint64_t)(ks * 2), dw + (uint64_t)(ks * 2), idesc_bf16(128, 256), acc);
            umma_ss(tmem + T_ACC + 256, dh + (uint64_t)(ks * 2), dw + (uint64_t)((256 * 128) >> 4) + (uint64_t)(ks * 2),
                    idesc_bf16(128, D_ > 256 ? D_ - 256 : 16), acc);
          }
        }
        tc_commit(&B.ws_empty);
        tc_commit(&B.h_empty);
        if (j == NCH - 1) tc_commit(&B.acc_full);
      }
      __syncwarp();
    }
  } else if (warp >= 4) {
    // ------------------------------------------------------------------------------------------ LayerNorm: three threads per row
    // (warps 4-7, 8-11, 12-15 a third of the columns each), fp32x2 arithmetic, the partial sums exchanged in shared memory
    {
      constexpr int HK = NKB / 3;
      const int r = (tid - 128) & (ROWS - 1), hf = (tid - 128) >> 7;
      float* ex = reinterpret_cast<float*>(sm + O_EX);
      const uint32_t gb = su + O_GB;
      mbar_wait(&B.x_full, 0);
      f2 s2[2] = {mk2(0.f, 0.f), mk2(0.f, 0.f)};
#pragma unroll
      for (int kb = 0; kb < HK; ++kb)
#pragma unroll
        for (int q = 0; q < 8; ++q) {
          const uint4 t = lds128(su + O_XN + (hf * HK + kb) * KBT + sw128(r, q));
          s2[0] = add2(s2[0], add2(unpack_bf16x2(t.x), unpack_bf16x2(t.y)));
          s2[1] = add2(s2[1], add2(unpack_bf16x2(t.z), unpack_bf16x2(t.w)));
        }
      const f2 st2 = add2(s2[0], s2[1]);
      ex[hf * ROWS + r] = lo2(st2) + hi2(st2);
      named_bar_sync(1, 384);
      const float mean = (ex[r] + ex[ROWS + r] + ex[2 * ROWS + r]) * (1.f / D_);
      const f2 nm2 = mk2(-mean, -mean);
      f2 v2[2] = {mk2(0.f, 0.f), mk2(0.f, 0.f)};
#pragma unroll
      for (int kb = 0; kb < HK; ++kb)
#pragma unroll
        for (int q = 0; q < 8; ++q) {
          const uint4 t = lds128(su + O_XN + (hf * HK + kb) * KBT + sw128(r, q));
          const uint32_t w4[4] = {t.x, t.y, t.z, t.w};
#pragma unroll
          for (int k = 0; k < 4; ++k) {
            const f2 d = add2(unpack_bf16x2(w4[k]), nm2);
            v2[k & 1] = fma2(d, d, v2[k & 1]);
          }
        }
      const f2 vt2 = add2(v2[0], v2[1]);
      ex[(3 + hf) * ROWS + r] = lo2(vt2) + hi2(vt2);
      named_bar_sync(1, 384);
      const float rs = rsqrtf((ex[3 * ROWS + r] + ex[4 * ROWS + r] + ex[5 * ROWS + r]) * (1.f / D_) + eps), cc = mean * rs;
      const f2 rs2 = mk2(rs, rs), ncc2 = mk2(-cc, -cc);
#pragma unroll
      for (int kb = 0; kb < HK; ++kb)
#pragma unroll
        for (int q = 0; q < 8; ++q) {
          const uint32_t ad = su + O_XN + (hf * HK + kb) * KBT + sw128(r, q);
          const uint4 t = lds128(ad);
          const uint32_t w4[4] = {t.x, t.y, t.z, t.w};
          const int col0 = (hf * HK + kb) * 64 + q * 8;          // gamma / beta of these 8 columns: 16-byte loads, not volatile
          const uint4 ga = lds128_nv(gb + col0 * 4), gc = lds128_nv(gb + col0 * 4 + 16);
          const uint4 ba = lds128_nv(gb + (D_ + col0) * 4), bc = lds128_nv(gb + (D_ + col0) * 4 + 16);
          const uint32_t g8[8] = {ga.x, ga.y, ga.z, ga.w, gc.x, gc.y, gc.z, gc.w}, b8[8] = {ba.x, ba.y, ba.z, ba.w, bc.x, bc.y, bc.z, bc.w};
          uint32_t o[4];
#pragma unroll
          for (int k = 0; k < 4; ++k) {
            const f2 g2 = mk2u(g8[2 * k], g8[2 * k + 1]), b2 = mk2u(b8[2 * k], b8[2 * k + 1]);
            const f2 y = fma2(unpack_bf16x2(w4[k]), mul2(rs2, g2), fma2(ncc2, g2, b2));   // (x rs - mean rs) g + b
            o[k] = pack_bf16(lo2(y), hi2(y));
          }
          sts128(ad, make_uint4(o[0], o[1], o[2], o[3]));
        }
      if (saver && hf == 0) { rstd[row0 + r] = rs; c1[row0 + r] = cc; }
      fence_proxy_async();
      named_bar_sync(1, 384);
      if (tid == 128) {
        mbar_arrive(&B.xn_full);
        if (saver) {
          for (int kb = 0; kb < NKB; ++kb) tma_store_2d(&mxn, su + O_XN + kb * KBT, kb * 64, row0);
          tma_store_commit();
          tma_store_wait_read0();
        }
        mbar_arrive(&B.xn_stored);
      }
    }
    if (warp >= 8 && warp < 12) {
      // ---------------------------------------------------------------------------------------- SwiGLU (one row per thread)
      const int r = tid - 256;
      const uint32_t trow = tmem + ((uint32_t)((warp & 3) * 32) << 16);
      const size_t grow = (size_t)(row0 + r);
      for (int j = 0; j < NCH; ++j) {
        mbar_wait(&B.ex_done, j & 1);
        tc_fence_after();
#pragma unroll 1
        for (int half = 0; half < 2; ++half) {
          uint32_t hp[16], ap[16], bp[16];
          {
            uint32_t av[32], bv[32];
            tmem_ld32(trow + T_AB + half * 32, av);
            tmem_ld32(trow + T_AB + 64 + half * 32, bv);
            tmem_wait_ld();
#pragma unroll
            for (int k = 0; k < 16; ++k) {
              const float a0 = __uint_as_float(av[2 * k]), a1 = __uint_as_float(av[2 * k + 1]);
              const float b0 = __uint_as_float(bv[2 * k]), b1 = __uint_as_float(bv[2 * k + 1]);
              hp[k] = pack_bf16(a0 * sigmoid_kit(a0) * b0, a1 * sigmoid_kit(a1) * b1);
              ap[k] = pack_bf16(a0, a1);
              bp[k] = pack_bf16(b0, b1);
            }
          }
          if (half == 1) {
            tc_fence_before();
            __syncwarp();
            if (lane == 0) mbar_arrive(&B.ab_free);
          }
          if (half == 0 && j >= 1) mbar_wait(&B.h_empty, (j - 1) & 1);
#pragma unroll
          for (int q = 0; q < 4; ++q)
            sts128(su + O_H + sw128(r, half * 4 + q), make_uint4(hp[4 * q], hp[4 * q + 1], hp[4 * q + 2], hp[4 * q + 3]));
          if (save) {
            const size_t off = grow * H_ + hs0 + j * 64 + half * 32;
#pragma unroll
            for (int q = 0; q < 4; ++q) {
              stg128(hs + off + q * 8, make_uint4(hp[4 * q], hp[4 * q + 1], hp[4 * q + 2], hp[4 * q + 3]));
              stg128(as_ + off + q * 8, make_uint4(ap[4 * q], ap[4 * q + 1], ap[4 * q + 2], ap[4 * q + 3]));
              stg128(bs + off + q * 8, make_uint4(bp[4 * q], bp[4 * q + 1], bp[4 * q + 2], bp[4 * q + 3]));
            }
          }
        }
        fence_proxy_async();
        __syncwarp();
        if (lane == 0) mbar_arrive(&B.h_full);
      }
      mbar_wait(&B.acc_full, 0);
      mbar_wait(&B.xn_stored, 0);                              // rank 0: the xn store has read the buffer the drain overwrites
      tc_fence_before();
    }
  }
  __syncthreads();                                             // this CTA's MMAs are done, its accumulator complete
#if CL == 1
  if (warp >= 4 && warp < 12) {
    // ------------------------------------------------------------------------------------------ one CTA per tile: the epilogue reads
    // the accumulator, adds the residual and stores (two threads per row, half of the columns each)
    tc_fence_after();
    const int r = (tid - 128) & (ROWS - 1), hf = (tid - 128) >> 7;
    const uint32_t trow = tmem + ((uint32_t)((warp & 3) * 32) << 16);
    const size_t grow = (size_t)(row0 + r);
    for (int c0 = hf * (D_ / 2); c0 < (hf + 1) * (D_ / 2); c0 += 32) {
      uint32_t v[32];
      tmem_ld32(trow + T_ACC + c0, v);
      const uint4* xp = reinterpret_cast<const uint4*>(xg + grow * D_ + c0);
      const uint4 x4[4] = {xp[0], xp[1], xp[2], xp[3]};
      tmem_wait_ld();
      uint4* op = reinterpret_cast<uint4*>(out + grow * D_ + c0);
#pragma unroll
      for (int i = 0; i < 4; ++i) {
        const uint32_t xw[4] = {x4[i].x, x4[i].y, x4[i].z, x4[i].w};
        uint32_t o[4];
#pragma unroll
        for (int k = 0; k < 4; ++k)
          o[k] = pack_bf16(bf16lo(xw[k]) + __uint_as_float(v[8 * i + 2 * k]), bf16hi(xw[k]) + __uint_as_float(v[8 * i + 2 * k + 1]));
        op[i] = make_uint4(o[0], o[1], o[2], o[3]);
      }
    }
    tc_fence_before();
  }
  (void)mpart;
#else
  const int prow0 = (tile * CL + rank) * ROWS;
  float acc[16 * NBX];                                         // thread (r, hf): columns k 32 + hf 16 + [0, 16) of the owned block
  if (warp >= 4 && warp < 12) {
    // ------------------------------------------------------------------------------------------ drain the other owners' blocks:
    // 32-column boxes, 16 columns per thread, each box TMA-stored to the scratch once drained; this CTA's own block goes to registers
    tc_fence_after();
    const int r = (tid - 128) & (ROWS - 1), hf = (tid - 128) >> 7;
    const uint32_t trow = tmem + ((uint32_t)((warp & 3) * 32) << 16);
#pragma unroll
    for (int k = 0; k < NBX; ++k) {
      uint32_t v[16];
      tmem_ld16(trow + T_ACC + rank * W_ + k * 32 + hf * 16, v);
      tmem_wait_ld();
#pragma unroll
      for (int i = 0; i < 16; ++i) acc[k * 16 + i] = __uint_as_float(v[i]);
    }
    constexpr int NB = D_ / 32, GB = 2;
    for (int b0 = 0; b0 < NB; b0 += GB) {
#pragma unroll
      for (int g = 0; g < GB; g += 2) {
        const int ba = b0 + g, bb = b0 + g + 1;
        uint32_t va[16], vb[16];
        const bool da = ba < NB && ba / NBX != rank, db = bb < NB && bb / NBX != rank;
        if (da) tmem_ld16(trow + T_ACC + ba * 32 + hf * 16, va);
        if (db) tmem_ld16(trow + T_ACC + bb * 32 + hf * 16, vb);
        tmem_wait_ld();
#pragma unroll
        for (int p = 0; p < 4; ++p) {
          if (da) sts128(su + O_RED + box_off(ba, r, hf * 4 + p), make_uint4(va[4 * p], va[4 * p + 1], va[4 * p + 2], va[4 * p + 3]));
          if (db) sts128(su + O_RED + box_off(bb, r, hf * 4 + p), make_uint4(vb[4 * p], vb[4 * p + 1], vb[4 * p + 2], vb[4 * p + 3]));
        }
      }
      fence_proxy_async();
      named_bar_sync(1, 256);
      if (tid == 128)
        for (int b = b0; b < b0 + GB && b < NB; ++b)
          if (b / NBX != rank) tma_store_2d(&mpart, su + O_RED + b * KBT, b * 32, prow0);
    }
    tc_fence_before();
    if (tid == 128) {
      tma_store_commit();
      tma_store_wait0();
      asm volatile("fence.proxy.async.global;" ::: "memory");
    }
  }
  __syncthreads();
  cluster_sync();                                              // every CTA's partial is in the scratch
  if (warp >= 4 && warp < 12) {
    // ------------------------------------------------------------------------------------------ owner: column block = this rank
    const int r = (tid - 128) & (ROWS - 1), hf = (tid - 128) >> 7;
    const size_t grow = (size_t)(row0 + r);
    if (tid == 128) {
      asm volatile("fence.proxy.async.global;" ::: "memory");
      mbar_expect_tx(&B.red_full, (CL - 1) * NBX * KBT);
      for (int c = 0; c < CL; ++c)
        if (c != rank)
          for (int k = 0; k < NBX; ++k)
            tma_load_2d(su + O_RED + (c * NBX + k) * KBT, &mpart, &B.red_full, rank * W_ + k * 32, (tile * CL + c) * ROWS);
    }
    uint2 xv[4 * NBX];                                          // the residual, loaded under the partials' transfer
#pragma unroll
    for (int k = 0; k < NBX; ++k)
#pragma unroll
      for (int p = 0; p < 4; ++p)
        xv[k * 4 + p] = *reinterpret_cast<const uint2*>(xg + grow * D_ + rank * W_ + k * 32 + hf * 16 + 4 * p);
    mbar_wait(&B.red_full, 0);
    for (int c = 0; c < CL; ++c) {                             // fixed order (own block first): deterministic
      if (c == rank) continue;
#pragma unroll
      for (int k = 0; k < NBX; ++k)
#pragma unroll
        for (int p = 0; p < 4; ++p) {
          const uint4 t = lds128_nv(su + O_RED + box_off(c * NBX + k, r, hf * 4 + p));
          float* a = acc + k * 16 + 4 * p;
          a[0] += __uint_as_float(t.x); a[1] += __uint_as_float(t.y); a[2] += __uint_as_float(t.z); a[3] += __uint_as_float(t.w);
        }
    }
#pragma unroll
    for (int k = 0; k < NBX; ++k)
#pragma unroll
      for (int p = 0; p < 4; ++p) {
        const uint2 x2 = xv[k * 4 + p];
        const float* a = acc + k * 16 + 4 * p;
        *reinterpret_cast<uint2*>(out + grow * D_ + rank * W_ + k * 32 + hf * 16 + 4 * p) =
            make_uint2(pack_bf16(bf16lo(x2.x) + a[0], bf16hi(x2.x) + a[1]), pack_bf16(bf16lo(x2.y) + a[2], bf16hi(x2.y) + a[3]));
      }
  }
#endif
  __syncthreads();
  if (warp == 2) { tc_fence_after(); tmem_dealloc(tmem, 512); }
}

// ================================================================================== wiring surface
// Built into a cubin by the newest nvcc that knows sm_100a and launched through the driver API from `transition_sm100.cu`;
// the dynamic shared-memory size the launch must request is exported here so the host never restates it.
extern "C" __device__ int transition_smem_bytes = SMEM_BYTES;
