// tswiglu_w.cu (research source: experiments/transition_fused_sm100/src/tswiglu_w.cu, branch perf/transition-sm100-b200; generated by export_engine.py)
// — the first kernel of the two-kernel Transition forward for D = 384 / 512 (H = 4D; -DDIM=<D>), sm_100a, bf16:
//   h = bf16(silu(a) b),  [a|b] = xn [Wa; Wb]^T (fp32), kit sigmoid        (the squeeze + residual is the second kernel)
// per (128-row tile, 128-unit hidden chunk j). 2-CTA tcgen05.mma as tgate_w.cu: the pair runs its own tiles in lockstep over the same
// chunk sequence; the leader issues M = 256, N = 256 products whose B operand is split by N (the leader holds Wa_j, the peer Wb_j,
// 128 rows each). xn and B stream through a ring in 64-column K-blocks (32 KB per stage and CTA). The accumulators ([a 128 | b 128])
// are double-buffered in tensor memory; the SwiGLU runs on two warpgroups (units 0..63 / 64..127) in two 32-unit steps and stages h
// in shared memory for TMA stores. SPDX-License-Identifier: Apache-2.0
#include "sm100.cuh"
using namespace s100;

#ifndef DIM
#define DIM 384
#endif
constexpr int D_ = DIM, H_ = 4 * DIM, HC = 128, NCH = H_ / HC, ROWS = 128, NKB = D_ / 64;
#ifdef SAVE_AB
constexpr int NST = 4;                                         // a / b staging takes a ring stage's room
#else
constexpr int NST = 5;
#endif
constexpr int KBT = ROWS * 128;                                // one K-block of a 128-row tile / of a 128-row weight half: 16 KB
constexpr int S_XN = 0, S_W = KBT, STAGE = 2 * KBT;
constexpr int O_ST = 0, O_OUT = NST * STAGE;                   // staging: h [128 rows][128 units] as two [128][64] tiles
#ifdef SAVE_AB
constexpr int O_AB = O_OUT + 2 * KBT;                          // a | b staging: [128][128] each as two [128][64] tiles
constexpr int O_BAR = O_AB + 4 * KBT;
#else
constexpr int O_BAR = O_OUT + 2 * KBT;
#endif
constexpr int SMEM_BYTES = O_BAR + 512;
static_assert(SMEM_BYTES <= 232448, "shared memory budget");
constexpr uint32_t IDESC = idesc_bf16(256, 256);

#define SIGF(a) sigmoid_kit(a)

struct Bars {
  uint64_t full[NST];
  uint64_t empty[NST], acc_full[2];
  uint64_t acc_empty[2];
  uint64_t staged[2], stage_free[2];                           // per warpgroup: its h / a / b staging tiles
  uint32_t tmem;
};

// maps: xn [M][D] (box 64 x 64); wa, wb [H][D] (box 64 x 128); h [M][H] (box 64 x 64)
extern "C" __global__ void __launch_bounds__(512, 1)
transition_swiglu_w_sm100(const __grid_constant__ CUtensorMap mxn, const __grid_constant__ CUtensorMap mwa,
                          const __grid_constant__ CUtensorMap mwb, const __grid_constant__ CUtensorMap mh,
#ifdef SAVE_AB
                          const __grid_constant__ CUtensorMap ma, const __grid_constant__ CUtensorMap mb, int save_ab,
#endif
                          int tiles) {
  extern __shared__ __align__(1024) uint8_t sm[];
  const uint32_t su = smem_u32(sm);
  Bars& B = *reinterpret_cast<Bars*>(sm + O_BAR);
  const int tid = threadIdx.x, warp = tid >> 5, lane = tid & 31;
  const int cta = blockIdx.x, G = gridDim.x;
  const int crank = (int)cluster_rank();
  const bool leader = crank == 0;
  auto count = [&](int k) { return (tiles > k) ? (tiles - k + G - 1) / G : 0; };
  const int n_valid = count(cta), n_local = count(cta & ~1);
  auto tile_of = [&](int i) { return i < n_valid ? cta + i * G : (n_valid > 0 ? cta + (n_valid - 1) * G : 0); };
#ifdef ITEM_SCHED
  // (tile pair, chunk) items dealt round-robin over the pairs of the grid: every SM gets work even when there are fewer tiles than SMs,
  // and the last round is at most one item deep. The pair's CTAs take tiles 2 t and 2 t + 1 of tile pair t.
  const int npairs = G >> 1, pair = cta >> 1, ntp = (tiles + 1) >> 1, ntot = ntp * NCH;
  const int nitem = (ntot > pair) ? (ntot - pair + npairs - 1) / npairs : 0;
  auto item_j = [&](int q) { return (pair + q * npairs) % NCH; };
  auto item_tile = [&](int q) { return 2 * ((pair + q * npairs) / NCH) + crank; };
  auto item_valid = [&](int q) { return item_tile(q) < tiles; };
  auto item_row = [&](int q) { const int t = item_tile(q); return (t < tiles ? t : tiles - 1) * ROWS; };
#else
  const int nitem = n_local * NCH;
  auto item_j = [&](int q) { return q % NCH; };
  auto item_valid = [&](int q) { return q / NCH < n_valid; };
  auto item_row = [&](int q) { return tile_of(q / NCH) * ROWS; };
#endif

  if (tid == 0) {
    for (int s = 0; s < NST; ++s) { mbar_init(&B.full[s], 1); mbar_init(&B.empty[s], 1); }
    for (int s = 0; s < 2; ++s) { mbar_init(&B.acc_full[s], 1); mbar_init(&B.acc_empty[s], 16); }   // 8 warps (both warpgroups) in each CTA of the pair
    for (int g = 0; g < 2; ++g) { mbar_init(&B.staged[g], 4); mbar_init(&B.stage_free[g], 1); }
    fence_barrier_init();
    prefetch_map(&mxn); prefetch_map(&mwa); prefetch_map(&mwb); prefetch_map(&mh);
  }
  if (warp == 2) { tmem_alloc2(smem_u32(&B.tmem), 512); tmem_relinquish2(); }
  tc_fence_before();
  __syncthreads();
  cluster_sync_relaxed();                                      // the barriers were published by fence_barrier_init
  tc_fence_after();
  const uint32_t tmem = B.tmem;

  if (warp < 4) setmaxnreg_dec<56>();
  if (warp == 0) {
    if (lane == 0) {
      const CUtensorMap* mab = leader ? &mwa : &mwb;
      int st = 0;
      for (int q = 0; q < nitem; ++q) {
        const int j = item_j(q), row = item_row(q);
        for (int kb = 0; kb < NKB; ++kb, ++st) {
          const int s = st % NST;
          if (st >= NST) mbar_wait(&B.empty[s], ((st / NST) - 1) & 1);
          if (leader) mbar_expect_tx(&B.full[s], 2 * STAGE);
          const uint32_t base = su + O_ST + s * STAGE;
#pragma unroll
          for (int h = 0; h < 2; ++h) tma_load_2d_2sm(base + S_XN + h * 8192, &mxn, &B.full[s], kb * 64, row + h * 64);
          tma_load_2d_2sm(base + S_W, mab, &B.full[s], kb * 64, j * HC);
        }
      }
    }
  } else if (warp == 1) {
    if (leader) {
      int st = 0;
      for (int q = 0; q < nitem; ++q) {
        const int s = q & 1, u = q >> 1;
        if (q >= 2) mbar_wait_cl(&B.acc_empty[s], (u - 1) & 1);
        for (int kb = 0; kb < NKB; ++kb, ++st) {
          const int sg = st % NST;
          mbar_wait(&B.full[sg], (st / NST) & 1);
          tc_fence_after();
          const uint32_t base = su + O_ST + sg * STAGE;
          const uint64_t dxn = desc_k128(base + S_XN), dw = desc_k128(base + S_W);
          if (elect_one()) {
#pragma unroll
            for (int ks = 0; ks < 4; ++ks)
              umma_ss2(tmem + s * 256, dxn + (uint64_t)(ks * 2), dw + (uint64_t)(ks * 2), IDESC, (kb > 0 || ks > 0) ? 1u : 0u);
            tc_commit2_mc(&B.empty[sg], 3);
            if (kb == NKB - 1) tc_commit2_mc(&B.acc_full[s], 3);
          }
          __syncwarp();
        }
      }
    }
  } else if ((warp >= 4 && warp < 8) || warp >= 12) {
    // SwiGLU: warps 4-7 units 0..63, 12-15 units 64..127, each in two 32-unit steps
    setmaxnreg_inc<152>();
    const uint32_t lb = (uint32_t)(warp & 3) * 32, r = lb + lane, trow = tmem + (lb << 16);
    const int half = warp >= 12 ? 1 : 0;
    for (int q = 0; q < nitem; ++q) {
      const int s = q & 1, u = q >> 1;
      mbar_wait(&B.acc_full[s], u & 1);
      tc_fence_after();
      uint32_t hp[32];
#ifdef SAVE_AB
      uint32_t ap[32], bp[32];                             // a, b rounded to bf16 for the backward (it does not recompute them)
#endif
#pragma unroll
      for (int st2 = 0; st2 < 2; ++st2) {
        uint32_t av[32], bv[32];
        tmem_ld32(trow + s * 256 + half * 64 + st2 * 32, av);
        tmem_ld32(trow + s * 256 + 128 + half * 64 + st2 * 32, bv);
        tmem_wait_ld();
#ifdef SAVE_AB
#pragma unroll
        for (int k = 0; k < 16; ++k) {
          ap[st2 * 16 + k] = pack_bf16(__uint_as_float(av[2 * k]), __uint_as_float(av[2 * k + 1]));
          bp[st2 * 16 + k] = pack_bf16(__uint_as_float(bv[2 * k]), __uint_as_float(bv[2 * k + 1]));
        }
#endif
#pragma unroll
        for (int k = 0; k < 16; ++k) {
          const float a0 = __uint_as_float(av[2 * k]), a1 = __uint_as_float(av[2 * k + 1]);
          const float b0 = __uint_as_float(bv[2 * k]), b1 = __uint_as_float(bv[2 * k + 1]);
          hp[st2 * 16 + k] = pack_bf16(a0 * SIGF(a0) * b0, a1 * SIGF(a1) * b1);
        }
      }
      tc_fence_before();
      __syncwarp();
      if (lane == 0) mbar_arrive_remote_relaxed(&B.acc_empty[s], 0);
      if (q >= 1) mbar_wait(&B.stage_free[half], (q - 1) & 1);
#pragma unroll
      for (int qq = 0; qq < 8; ++qq)                       // this warpgroup's 64 units = one [128][64] staging tile
      {
        sts128(su + O_OUT + half * KBT + sw128(r, qq), make_uint4(hp[4 * qq], hp[4 * qq + 1], hp[4 * qq + 2], hp[4 * qq + 3]));
#ifdef SAVE_AB
        sts128(su + O_AB + half * KBT + sw128(r, qq), make_uint4(ap[4 * qq], ap[4 * qq + 1], ap[4 * qq + 2], ap[4 * qq + 3]));
        sts128(su + O_AB + (2 + half) * KBT + sw128(r, qq), make_uint4(bp[4 * qq], bp[4 * qq + 1], bp[4 * qq + 2], bp[4 * qq + 3]));
#endif
      }
      fence_proxy_async();
      __syncwarp();
      if (lane == 0) mbar_arrive(&B.staged[half]);
    }
  } else if (warp == 8 || warp == 9) {
    // one store thread per SwiGLU warpgroup (t = its 64 units): the two stage and store independently
    if (lane == 0) {
      const int t = warp - 8;
      for (int q = 0; q < nitem; ++q) {
        const int j = item_j(q);
        mbar_wait(&B.staged[t], q & 1);
        if (item_valid(q)) {
          const int row = item_row(q);
#pragma unroll
            for (int h = 0; h < 2; ++h) {
              tma_store_2d(&mh, su + O_OUT + t * KBT + h * 8192, j * HC + t * 64, row + h * 64);
#ifdef SAVE_AB
              if (save_ab) {
                tma_store_2d(&ma, su + O_AB + t * KBT + h * 8192, j * HC + t * 64, row + h * 64);
                tma_store_2d(&mb, su + O_AB + (2 + t) * KBT + h * 8192, j * HC + t * 64, row + h * 64);
              }
#endif
            }
          tma_store_commit();
          tma_store_wait_read0();
        }
        mbar_arrive(&B.stage_free[t]);
      }
      tma_store_wait0();
    }
  }
  tc_fence_before();
  __syncthreads();
  cluster_sync_relaxed();
  if (warp == 2) { tc_fence_after(); tmem_dealloc2(tmem, 512); }
}

// ================================================================================== wiring surface
// Built into a cubin by the newest nvcc that knows sm_100a and launched through the driver API from `transition_sm100.cu`;
// the dynamic shared-memory size the launch must request is exported here so the host never restates it.
extern "C" __device__ int transition_smem_bytes = SMEM_BYTES;
