"""The committed sweep page has to say what the repository says.

`docs/autotune-sweep-grid.html` is generated by `miniworld_engine.viz.sweep_page` from
registry.csv, the config sets and the tuned cache. A generated file that is committed rots the
moment someone edits a ladder and forgets it, and this one rotted twice in an afternoon while it
was maintained by hand: once it showed a narrowing the CSVs did not carry, once a dtype the
registry had already dropped. Both times the page was the thing being read to make a decision.

So the numbers are checked rather than trusted. This compares the totals the page states against a
fresh `collect()` -- kernel count, unit count, and the size of the sweep -- which is what changes
when a ladder, a shape list or a dtype column moves. Regenerate with:

    python -m miniworld_engine.viz.sweep_page
"""
from __future__ import annotations

import re

import pytest
from paths import ROOT

from miniworld_engine.viz.sweep_page import collect

PAGE = ROOT / "docs" / "autotune-sweep-grid.html"


@pytest.fixture(scope="module")
def stated() -> dict[str, str]:
    if not PAGE.is_file():
        pytest.fail(f"{PAGE} is missing; run `python -m miniworld_engine.viz.sweep_page`")
    text = PAGE.read_text()
    return dict(re.findall(r"<dt>([^<]+)</dt><dd class=\"num\">([^<]+)</dd>", text))


def test_the_page_counts_the_kernels_the_build_drives(stated) -> None:
    _rows, totals = collect()
    said = stated.get("kernels covered", "")
    assert said.endswith(f"of {totals['kernels']}"), (
        f"the page says {said!r} kernels, the repository has {totals['kernels']}. "
        f"Regenerate: python -m miniworld_engine.viz.sweep_page")


def test_the_page_states_the_current_sweep_size(stated) -> None:
    """Both numbers, because they are different questions and the page used to answer neither.

    `module invocations declared` is what `build all` starts -- one module invocation per row of
    registry_module.csv. `cache keys required` is what it produces -- one per row of
    registry_kernel.csv. The page read `op_units()` for both and so reported the per-kernel driver
    ladders, which the module sweep replaced: 4,948 units over 67 kernels for a build that runs
    6,526 over 60."""
    _rows, totals = collect()
    assert stated.get("module invocations declared") == f"{totals['units']:,}", (
        f"the page says {stated.get('module invocations declared')!r} units, the repository plans "
        f"{totals['units']:,}. Regenerate the page.")
    assert stated.get("cache keys required") == f"{totals['buckets']:,}", (
        f"the page says {stated.get('cache keys required')!r} entries, the derivation names "
        f"{totals['buckets']:,}. Re-run `dev derive`, then regenerate the page.")
    assert stated.get("buckets × grid") == f"{totals['cost'] / 1e6:.2f} M", (
        f"the page says {stated.get('buckets × grid')!r}, the repository is "
        f"{totals['cost'] / 1e6:.2f} M (config, shape). Regenerate the page.")


def test_every_row_the_build_drives_is_on_the_page(stated) -> None:
    """A kernel added to registry.csv and not to the page is the drift that matters most: the page
    reads as a complete inventory, so a missing row is invisible rather than obviously wrong."""
    rows, _totals = collect()
    text = PAGE.read_text()
    missing = [r["kernel"] for r in rows if f">{r['kernel']}</span>" not in text]
    assert not missing, f"kernels the build drives but the page does not list: {missing}"
